### ISSUE TITLE
Pb Install on Synology DS 212J

### ISSUE THREAD

**Issue by Nocilus** [PokemonGoMap/PokemonGo-Map#657] opened 2016-08-14 12:18 UTC
Hi All,

i already post this on "DiscordApp - Help", but i understand, that my request is an issue ... so i try here ;)

Here is my pb : 

Hi Everyone, I would like to know, if someone here, arrive to install "PokemonGo-Map" on a Synology DS 212J ? 

I have this version : 
DSM 6.0.1-7393 Update 2 
Python 2.7.11 
Pip 8.1.2 
PyLoad 0.4.9-4 

And a error here : 
Using cached pycryptodomex-3.4.2.tar.gz Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 13)) Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 17)) Using cached pyproj-1.9.5.1.tar.gz Complete output from command python setup.py egg_info: unable to execute '/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc': No such file or directory using bundled proj4.. Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-build-cH7MM7/pyproj/setup.py", line 72, in <module> objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c']) File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts) File "/usr/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile raise CompileError, msg distutils.errors.CompileError: command '/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc' failed with exit status 1
---------------------------------------- Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cH7MM7/pyproj/ 

Thanks you so much
(and sorry if my english is poor :))

Best Regards
Nocilus

**Comment by annessi** [comment] 2016-08-14 14:20
Use Docker to run it on Synology.

**Comment by Nocilus** [comment] 2016-08-14 15:38
Thanks for this answer.

I Can't find Docker on my Synology DS 212J because of this : 

"
it looks like only 64 bit models support docker.
https://www.synology.com/en-us/dsm/app_packages/Docker has list of supported models

Applied Models

16-Series : RS18016xs+
15-series : RC18015xs+, RS815(RP)+, DS3615xs, DS2415+, DS1815+, DS1515+, DS415+
14-series : RS3614xs+, RS3614(RP)xs, RS2414(RP)+, RS814(RP)+
13-series : RS10613xs+, RS3413xs+, DS2413+, DS1813+, DS1513+, DS713+
12-series : RS3412(RP)xs, RS2212(RP)+, RS812(RP)+, DS3612xs, DS1812+, DS1512+, DS712+, DS412+
11-series : RS3411(RP)xs, RS2211(RP)+, DS3611xs, DS2411+, DS1511+, DS411+II, DS411+
10-series : RS810(RP)+, DS1010+, DS710+
"

Any other ideas ? :)

Best Regards
Nocilus

**Comment by ingtellect** [comment] 2016-08-17 01:06
I tried to install it on the DS214+ but had bunch of errors while installing python packages. If I fix one issue another one came up. After I struggled couple hours I gave it up and installed it on MBP. I'm not sure it's impossible but it think it will take tons of time and works.

**Comment by pyr0ball** [comment] 2016-08-20 08:18
Other system dependencies are not met. Very likely you will need to install them from source. Check out the [Debian 7/8 guide](https://pgm.readthedocs.io/en/develop/basic-install/linux.html)

Closing issue here as it is not a bug. We'll have a support forum up for similar posts soon

**Closed by pyr0ball** 2016-08-20 08:18 UTC
Labels: issues are not for support!, not a bug - server issue
