### ISSUE TITLE
-ss spawn.json takes more than 1 minute from search to upsert

### ISSUE THREAD

**Issue by Saprophator** [PokemonGoMap/PokemonGo-Map#743] opened 2016-08-16 18:12 UTC
## Expected Behavior

-ss spawn.json is accelerating scanning speed
time between search and upsert should be <5 seconds
adding accounts should increase overall scan speed

## Current Behavior

-ss spawn.json is taking more than 1 minute between search and upsert per worker
gets worse with adding accounts
is 1/4 th of the speed than the original spawn scan implementatin from reddit 
[https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/](https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/)

## Possible Solution

fix the bug that slows things down :P
## Steps to Reproduce (for bugs)

1. Use -ss spawn.json
2. compare with the original implementation

## Context

Scan queue builds up and 3/4th of the pokemon are not found
## Your Environment

* Version used: current development branch on Linux, older development branch with modified search.py on Windows
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
I currently have a VPS with the new commit running Debian 8
I still have the old Implementation on my Windows 10 machine

## Files to compare
New Implementation http://pastebin.com/EXrRksg9
Old Implementaion http://pastebin.com/h4h14959
Old search.py http://pastebin.com/4wPAUcmb

## command line used
python runserver.py -nsc -fl -L de -k myKey -l "myLoc" -st 1 -sd 10 -ss spawns.json -a ptc -u /30 accounts/ -p  --db-ty mysql --db-name --db-user --db-pass --db-host --db-port --db-max_connections

**Comment by Toetje585** [comment] 2016-08-16 18:20
Confirmed, here aswell on Ubuntu Server 16.04 seems like something is wrong when you add -ss to more workers.

**Comment by aldarund** [comment] 2016-08-16 18:31
Have 3x less pokemons with -ss than with --spawnpoints-only. All other settings are same. Queue size not  increasing, its less than 5 always usually 0.

**Comment by Infernoman** [comment] 2016-08-16 18:32
Can confirm.

**Comment by FeikoWielsma** [comment] 2016-08-16 18:34
I have the same, or atleast a similar problem. If I used my old spawns.json (which that old set.py script generated for me) the issue seems to go away, though.

**Comment by Infernoman** [comment] 2016-08-16 18:39
This will help with the queue issue but not the slow scanning issue. https://github.com/PokemonGoMap/PokemonGo-Map/pull/741

**Comment by Zentriert** [comment] 2016-08-16 18:49
Is this because TBTerra initially had it set to 60s by default? I know the [script set.py](https://gist.github.com/cramk/c0e0b0e8466b28141033ba14d4a1b88e) from Reddit that everyone was using has the option to change the delay from 60s to 5s and I was using that.

**Comment by Infernoman** [comment] 2016-08-16 18:50
@Zentriert is this the line your referring to? https://github.com/PokemonGoMap/PokemonGo-Map/pull/741/files#diff-6c43bfb0a183e3412f838ddd49606dbdL273

**Comment by justinkwaugh** [comment] 2016-08-16 19:14
@aldarund it could be this issue: https://github.com/PokemonGoMap/PokemonGo-Map/issues/747

**Comment by Toetje585** [comment] 2016-08-16 22:06
2016-08-16 23:59:52,816 [ss_search_worker_0][        models][    INFO] Upserted 1 pokemon, 0 pokestops, and 0 gyms
2016-08-17 00:00:02,817 [ss_search_worker_0][        search][    INFO] Searching step 5530, remaining 244
2016-08-17 00:02:00,051 [ss_search_worker_1][        models][    INFO] Upserted 1 pokemon, 0 pokestops, and 0 gyms
2016-08-17 00:02:10,062 [ss_search_worker_1][        search][    INFO] Searching step 5531, remaining 446
2016-08-17 00:04:07,309 [ss_search_worker_2][        models][    INFO] Upserted 1 pokemon, 0 pokestops, and 0 gyms

**Comment by TBTerra** [comment] 2016-08-16 22:34
ok, the best thing i can think of to narrow it down (much easyer to fix if we can identify the code that causingt he slow down) is to add amny other log messages throughout the loop (not just at the begining and the end), that way we can get the place where its stalling to within a few lines of code

**Comment by Toetje585** [comment] 2016-08-16 23:12
[nohup.txt](https://github.com/PokemonGoMap/PokemonGo-Map/files/421490/nohup.txt)

**Comment by Toetje585** [comment] 2016-08-16 23:38
I just removed my webhook and now it works, looking into it.

**Comment by brandonshults** [comment] 2016-08-17 03:40
This is certainly an issue with webhooks, and isn't specific to ss mode.  Indeed, I believe this issue is at the root of many mysterious "slow speed" complaints.  If you define a webhook, but don't actually have a server set to process that webhook the post will hang and block the thread.

A potential solution would be to make the webhook post asynchronous with grequests

**Comment by rrbailey89** [comment] 2016-08-17 04:18
@brandonshults @toetje585 your encountering the slowdown after defining webhook in your worker/server command line? Or config.ini or from running a standalone webhook?

**Comment by brandonshults** [comment] 2016-08-17 04:21
I encounter the issue when defining a webhook in config.ini, but not actually running a server to take the requests at the address.

**Comment by rrbailey89** [comment] 2016-08-17 04:24
@brandonshults I see. This must be why I have not encountered an issue. I define in config.ini and always run the webhook server too

**Comment by brandonshults** [comment] 2016-08-17 04:26
If you kill your webhook I'm willing to bet you will see your workers slow down to one request per minute

**Comment by MatthiasDING** [comment] 2016-08-17 05:34
I have never defined a webhook, but I still have the problem of one request per minute for each ss_search_worker.

**Comment by Toetje585** [comment] 2016-08-17 07:50
@rrbailey89  I did it in the config.ini when the issue persist  and now i'm using it in the command line. As-long as you start the web-hook service first you should be good to go.  I didn't try to kill it while running the map trough. However I believe @Saprophator was not using any webhooks.

**Comment by Saprophator** [comment] 2016-08-17 10:40
This is definately not related to webhooks. I wasn't using webhooks at the time (see command line in the issue description). I'm currently using a webhook with the old search.py without any measurable influence on the scan time.

**Comment by jccwright** [comment] 2016-08-17 10:53
There needs to me a messaging bus unrelated to this application, or at
least running independently of the scanning. Basically the scanner workers
should dump and go and leave the queuing and database management to
something more equipped for it... like a messaging bus.

I have an idea and I plan implementing a PoC before requesting a PR. There
are several secondary purposes behind my plan which I will get into during
my proposal but for now if there is anyone who might be interested when I
present my solution please ping me directly so I can update you all easily.

**Comment by Saprophator** [comment] 2016-08-17 10:59
@jccwright Count me in. I could also help testing stuff if needed.

**Comment by Infernoman** [comment] 2016-08-17 16:38
The login delay was affecting the scan delay with more than one user, I've made a fix in #750 but would love some opinions.

**Comment by justinkwaugh** [comment] 2016-08-17 17:58
One thing I noticed is that parse_lock has a broader scope than is necessary if it is really meant to be used as a db lock.  If it was passed in to the parse_map method and then just used around the db part, it would remove the webhook calls from the lock

**Comment by Saprophator** [comment] 2016-08-17 19:09
I tried #750 on my 40 account setup and it didn't accelerate the scanning.
[consolelog](http://pastebin.com/K0Q4HH1Z)

**Comment by TBTerra** [comment] 2016-08-17 19:19
once it is finished and merged #582 may solve the issue as it removes locks in favor of queues and a dedicated db write and webhooks threads

**Comment by Saprophator** [comment] 2016-08-17 21:40
@TBTerra that still wouldn't explain why the old implementation from that reddit thread is so much faster.
Something must have changed. I made additional measurements and its roughly 7 times faster with the same amount of accounts.

**Comment by zimpixa** [comment] 2016-08-18 11:21
I had same issue, yet fixed it with updating Python from 2.7.11 to 2.7.12; Nodejs from 4.5.1. to 6.3 and PIP from 7.1.2 to 8.1.2 then build up fresh copy.

**Comment by Saprophator** [comment] 2016-08-18 19:45
@Infernoman #750 is fixing this issue to a degree. I tried it on my windows system with the latest development version and the fix and its working fine. Queue stays empty, searches and upserts follow quickly. It's still slow as f*ck on my VPS but I think that might be database related by now... Unsure where that might suddenly come from.

**Comment by Infernoman** [comment] 2016-08-18 19:52
@Saprophator I completely agree it does not fix the issue 100%. after a certain number of workers it seems the database can no longer keep up. With a combination of #582, #750 and #785 it greatly increases yet again. but still nowhere near what's specified when using -sd.

Keep in mind im testing with 400 accounts at a time. and a single remote database,

**Comment by XyrusX** [comment] 2016-08-19 18:55
@Infernoman Might be a stupid question... Is there a way to dump the existing db into a spawns.json file? Everytime I update my branch i have to rescan all spawn points.

**Comment by teknicsrx7** [comment] 2016-08-20 08:24
@XyrusX set.py still works to dump db into spawns.json,  but that feature is also now built into the command line for the map

**Comment by andrewli-ca** [comment] 2016-08-21 00:46
Possible fix:

Search for "while timeDif(curSec(), spawns[pos]['time']) < 60:" in search.py(line #423) and change 60 to 5. 

TBTerra originally had it at 5.

**Comment by Infernoman** [comment] 2016-08-21 02:24
^ wont fix the issue. wait until #890 is merged

**Closed** 2016-08-26 06:46 UTC
