### ISSUE TITLE
[Feature Request] Toggle "Hide Pokemon" filter

### ISSUE THREAD

**Issue by DragnHntr** [PokemonGoMap/PokemonGo-Map#1189] opened 2016-09-07 02:35 UTC
I would like the ability to un-hide the list of hidden pokemon without having to remove the whole list and then add it back after. Perhaps a toggle switch for the hidden list that temporarily disables it.

Even cooler would be a second list of hidden pokemon that has a toggle (or perhaps both) so I can, for example, put pidgeys, caterpies, weedles on the second list and normally have it hidden, but be able to easily toggle it off temporarily to see if there are any high-xp value pokemon nearby.

Just an idea to add some more versatility to hidden pokemon.

**Comment by rawdr** [comment] 2016-09-07 19:25
Agreed - had this same thought a few days ago. I've looked into the html/JS enough to find where to add my own defaults to the hidden list, but having a toggle-able groups would be ideal.

**Comment by beccasafan** [comment] 2016-09-23 22:52
Duplicate of 1123.

**Closed by beccasafan** 2016-09-23 22:52 UTC
Labels: duplicate, feature request, frontend
