### ISSUE TITLE
Pokémon Stacking

### ISSUE THREAD

**Issue by blackhattristar** [PokemonGoMap/PokemonGo-Map#587] opened 2016-08-13 07:05 UTC
Pokémon are appearing on top of each other and not moving. I've noticed all the Pokémon that are stacked are Pokémon that show 500+ hours left until they disappear.
## Expected Behavior

Pokémon should seperate when you zoom in on the map. 
## Current Behavior

Pokémon are stacking on top of each other in the same location.
<img width="158" alt="screen shot 2016-08-13 at 12 03 52 am" src="https://cloud.githubusercontent.com/assets/13209070/17641964/a042a266-60e9-11e6-9eaf-5130d8b0a031.png">

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by numb401** [comment] 2016-08-13 07:15
Dupe of #556, please read other issues before posting.

**Comment by blackhattristar** [comment] 2016-08-13 07:18
@numb401 I don't believe #566 is a dupe. #566 does not mention stacking Pokémon. I just noticed that the ones stacked happen to also be the 500+ hour Pokémon.

**Comment by NGPriest** [comment] 2016-08-13 07:25
It is a dupe of #566, wouldn't #587 won't happen if #566 is resolved...

**Comment by blackhattristar** [comment] 2016-08-13 07:29
@NGPriest I guess we'll find out once #566 is resolved. Apparently it is but I'll test it once the pull request is accepted.

**Closed** 2016-08-13 08:42 UTC
Labels: duplicate
