### ISSUE TITLE
Scanner keeps searching

### ISSUE THREAD

**Issue by KyleBoyer** [PokemonGoMap/PokemonGo-Map#1142] opened 2016-09-04 23:00 UTC
The map scan status fetching occurs every 5 seconds, yet even when nothing is fetching the map, it keeps scanned. Essentially, the map scan status fetching is a heartbeat. This means that after a period of time, with no heartbeat, the scanner should auto-stop the search to preserve the accounts from being banned. 

## Expected Behavior
1. (Start scanner python script["runserver.py"])
2. Open map web UI, scanner begins scanning.
3. Close map web UI, scanner stops scanning.
Repeat 2-3

## Current Behavior
The map continues scanning regardless of the heartbeat.

## Possible Solution
Call `post_search_control("off")` after a heartbeat has been absent for X time(60 seconds)

## Steps to Reproduce (for bugs)
1. Start scanner python script("runserver.py")
2. Open Web UI
3. Close Web UI

## Context
I have a shared scanner running, and only a few people use it. Thus, the scanner application is running 24/7. The accounts used for this scanner are banned quickly, after one night of leaving the search on.

## Your Environment
* Version used: Latest as of Sunday, September 4th, 2016 at 6PM CST
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Ubuntu 16.04 - Desktop

**Comment by justsomedudeonthenet** [comment] 2016-09-04 23:45
This is not desired behaviour for many of us.  I want it tracking every single pokemon that spawns in my city so I have it for statistical analysis.

**Comment by LordNeoZ** [comment] 2016-09-04 23:56
You're not getting the accounts banned due to running 24/7 but for being teleported by 2 or more people moving the marker at the same/adjacent time. Most of us run the scanner 24/7 to get statistics/heatmaps without getting banned. You should consider to split your workers and configure 1 scanner per person or add workers and extend the area (but with fixed location)

**Comment by KyleBoyer** [comment] 2016-09-05 00:09
Prior to having it be a shared map, I still had this issue. However, it appears to be a new type of ban - accounts can still login, and fetch pokestop and gym locations, but no Pokémon. I switch accounts used, and it actually picks up on the Pokémon. I had this happen when running on my local machine(not shared), overnight. I understand some people would not like this behavior, but all that needs to be done is add a --heartbeat-timeout(or -hb) argument(0 being no timeout).

**Comment by LordNeoZ** [comment] 2016-09-05 01:11
That could be a soft ip ban, try to use a proxy because your IP was probably already flagged.

**Comment by DiscoTim** [comment] 2016-09-05 01:55
I think you are basically asking for this, which i think would be a great feature for a lot of people: https://github.com/PokemonGoMap/PokemonGo-Map/issues/1132

**Comment by KyleBoyer** [comment] 2016-09-05 02:55
Yes, that is basically what I'm thinking of. I do not think it was a soft IP ban, because immediately after switching to different accounts, it ran as expected. Additionally, those accounts still, to this day, do not display any pokemon when scanning.

**Comment by justsomedudeonthenet** [comment] 2016-09-06 22:03
Closing as duplicate of #1132

**Closed by justsomedudeonthenet** 2016-09-06 22:03 UTC
