### ISSUE TITLE
database with >10gb jelastic

### ISSUE THREAD

**Issue by schadis** [PokemonGoMap/PokemonGo-Map#153] opened 2016-08-08 14:40 UTC
## Expected Behavior

database should clean itself if expired

## Current Behavior

My Database on Jelastic is growing and getting bigger and bigger and i downt know why

## Possible Solution
???

## Steps to Reproduce (for bugs)
install acoording 1.)https://www.reddit.com/r/pokemongodev/comments/4wnjfq/pokemongomap_reborn_jelastic_deploy_multi/
2.)add 20 accounts
3.) let it run
4.) 10gb are free for the app and they are reached in 20 min to 30 mins (never had that problem localy)

**Comment by EdenGottlieb** [comment] 2016-08-08 14:46
Adding -cd to the parameters cleans the database.

**Comment by schadis** [comment] 2016-08-08 14:49
will try and report

**Comment by schadis** [comment] 2016-08-08 15:41
running the server no with -cd but the database is still growing and growing

**Comment by invisiblek** [comment] 2016-08-08 15:46
https://github.com/PokemonGoMap/PokemonGo-Map/pull/160

**Comment by schadis** [comment] 2016-08-08 15:48
y thats for the data weeks ago but my webserver space with 10 gb is full in 20-30 mins

**Comment by BaIthamel** [comment] 2016-08-09 00:36
Why are you asking here if the issue is with someone else's repo? I'll reopen if you give me a good reason otherwise i'm closing this for now.

**Closed by BaIthamel** 2016-08-09 00:36 UTC

**Comment by schadis** [comment] 2016-08-09 06:03
Clause the jelastic link from this repo is Linked to his
