### ISSUE TITLE
Account shows 0 0 0 but no captcha required(account is asking for captcha 10 min later)

### ISSUE THREAD

**Issue by PeshBG** [PokemonGoMap/PokemonGo-Map#1639] opened 2016-12-18 11:03 UTC
Since i updated to the latest dev today, some of my accounts state that they need captcha or are banned but when i run the pogo captcha check it shows no captcha needed. Some time later 5 10min , the account requests the captcha and it starts working again... anyone else having the same issue?

**Comment by PeshBG** [comment] 2016-12-18 13:22
issue is not appearing on my old build...

**Comment by TheNewDarkOne** [comment] 2016-12-21 11:06
i think the problem, at least with speedscan. it assumes 0 0 0 is bad. but sometimes in rural areas, 0 0 0 is actually accurate. but scanner doesn't know diff between the two sadly. no way to

**Comment by m3g4mInD** [comment] 2016-12-26 21:02
I have the same ,new map install  default branch  after 15 mnts return bad scan 0/0/0 and even i try  check captchas dont have any captchas, after 1h check captchas all accts have captcha weird.

**Comment by dikkedeur** [comment] 2016-12-27 15:08
i have kinda the same, with the new speed v2 i have this within 15 minutes, then the more workers have logged in ( it takes some time it seems ) they have all this in no time.
im not in rural area.
what happens is that it looks like they are banned, i need to wait 2 hours ( so it seems like a ban ) with -bh i dont have this problem.

**Comment by m3g4mInD** [comment] 2016-12-29 23:07
12 days with this problem in dev branch and they dont fix!!!? I have made a fix for this, just enjoy discord and look for @testing*guy  i can send the files  :)

**Comment by sebastienvercammen** [comment] 2016-12-30 17:38
> 12 days with this problem in dev branch and they dont fix!!!? I have a fix for this, just enjoy discord and look for @testing*guy i can send the files :)

@m3g4mInD Sending potentially malicious files via private message on Discord that supposedly contains a fix is not how open source works.

This issue hasn't been on top of the priority list and anyone is free to contribute to open source. If a PR would exist that really does fix it (with proper research and testing), it would have been merged the day it was ready.

I suggest changing your open source strategy if you want things to get fixed faster.

**Comment by m12lrpv** [comment] 2016-12-31 20:22
I've been playing with this issue and all that is needed is to retrieve the captch url after an empty scan. If you get one then it's a captcha if you don't then it's not.

`
                        parsed = parse_map(args, response_dict, step_location, dbq, whq, api, account)
                        #search_items_queue.task_done()
                        if parsed['count'] > 0:
                            status['success'] += 1
                            consecutive_empties = 0
                        else:
                            status['noitems'] += 1
                            consecutive_empties += 1
                            parsed = False
                            status['fail'] += 1
                            consecutive_fails += 1
                            status['message'] = 'Map parse failed at {:6f},{:6f}, abandoning location. {} may be banned.'.format(step_location[0], step_location[1], account['username'])
                            log.exception(status['message'])

                            # this bombed once and needs a try catch block
                            try:
                                captcha_url = captcha_request(api)
                                log.info(account['username']+ ' ' + captcha_url)
                                filename = "userlogs/log_%s.log" % (account['username'])
                                with open(filename, "a") as myfile:
                                    myfile.write(" -------------- Zero Scan --------------\n")                                

                            except Exception as e:
                                #log.error(repr(e))
                                log.error('Unable to get Captcha URL')

                            if captcha_url and len(captcha_url) > 1:
                                status['message'] = 'Account {} is encountering a captcha, starting 2captcha sequence'.format(account['username'])
                                log.warning(status['message'])
                                break_for_new_user = True`

I'd put togeter a fork and a pull request but some idiot went through and put full stops through the comments in the codebase and that's too much merging to have to go through.
It's unfortunate because I also have intermediate scans for speed limiting because a time delay doesn't really work without it and why wait when you can scan. Also static scans with a list of fixed scan locations because who wants to scan places that just have pidgy's and a 'follow the leader' worker where workers will all scan one after the other in a line.

**Comment by m12lrpv** [comment] 2016-12-31 21:44
The cause is definitely a behavioural issue and one i'm still investigating and speed isn't the problem because I get them with accounts that are just standing still in a fixed static location.
Prevention is slightly out of our grasp at the moment so i'm working on more efficient handling by detecting empty scans v's actual captchas. I found repeated use of the user after an empty scan would definitely result in a captcha on the next scan (the scan was in a different location, havent tested same location) so in some respects the empty scan serves as a warning. I implemented that an empty scan results in the user being dropped from active duty. That cut the actual captchas's down by 50%.

**Comment by kevdotcom** [comment] 2017-01-03 20:49
Whenever I get this problem and switch out the accounts it always goes away... I think it's mostly an account problem.

**Comment by Imoq** [comment] 2017-01-09 12:41
Upgraded to latest devel and started using 0.51, and now 4 (of around 70 active accounts) get 0/0/0 at all times; but the accounts are fine. This is definitely something to look at, just not sure where to start...

**Comment by sebastienvercammen** [comment] 2017-01-18 00:18
Handling scans has been reworked, any remaining bad scan is because of an IP/account ban.

To get the latest version:
```
git pull
pip uninstall pgoapi
pip uninstall protobuf_to_dict
pip uninstall protobuf3-to-dict
pip install -r requirements.txt --upgrade
```

**Closed by sebastienvercammen** 2017-01-18 00:18 UTC
