### ISSUE TITLE
Notifications popping up inappropriately.

### ISSUE THREAD

**Issue by marcmicalizzi** [PokemonGoMap/PokemonGo-Map#363] opened 2016-08-09 23:43 UTC
At some point recently the notifications got broken. Now every time a pokemon is added to the map, the last notification comes up.

I.e.

1. First notification for an Arcanine appearing happens
2. Arcanine expires
3. Every time a new pokemon is added to the map "A wild Arcanine appeared!" at the location of the expired arcanine.

This is on develop branch, currently on commit 3155b50953b4b9252b328dfcf03b2fe9c82b4749 (which is unrelated)

EDIT: It possibly stops after the search is repeated on the previous cell which contained the notification pokemon. After 50 or so notifications it just stopped for me.

EDIT EDIT: It only happens after the notification pokemon expires.

**Comment by imynwulf** [comment] 2016-08-10 00:46
This is a duplicate issue. #148  Please search before posting new issues.

**Comment by marumari** [comment] 2016-08-10 03:28
Also a duplicate of the more descriptive #215, which has a patch that seems to work.

**Closed** 2016-08-10 04:08 UTC
