### ISSUE TITLE
Spawntracker working with current dev branch

### ISSUE THREAD

**Issue by shiznewski** [PokemonGoMap/PokemonGo-Map#508] opened 2016-08-11 16:54 UTC
2 days ago i implemented the spawntracker version from https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/

It only scans known spawn points at their spawn time. Today digital ocean ips got blocked so i needed to update my branch to the current dev branch for proxies and now it doesn't work.
This is way over my head but is there any change of getting this added it? or is there a way to make it work. This spawntracker code doesn't seem to use the proxy to send the request.

**Comment by marumari** [comment] 2016-08-11 16:58
Duplicate of #179, I believe.

**Closed** 2016-08-12 18:03 UTC
Labels: duplicate
