### ISSUE TITLE
Setting locations in config.ini doesn't work

### ISSUE THREAD

**Issue by symphys** [PokemonGoMap/PokemonGo-Map#858] opened 2016-08-19 22:53 UTC
When specifying the locations in config.ini the script is not working.
Even a simple -h results in an error:
runserver.py: error: location can't be set to a list ... unless its action type is changed to 'append'

## Expected Behavior
Set locations in config.ini should eliminate the need to specify them at the cmdline.

## Current Behavior
runserver.py: error: location can't be set to a list '["48.179459, 11.547390", "48.179459, 11.567390"]' unless its action type is changed to 'append'

## Steps to Reproduce (for bugs)
1. change config.ini locations.
2. run python runserver.py -h

**Comment by justsomedudeonthenet** [comment] 2016-08-19 22:55
Location is supposed to be a single value.

Use `location = "48.179459, 11.547390"`

**Comment by symphys** [comment] 2016-08-19 23:06
Then the config.ini.example is wrong.
And how to use this with a beehive?

**Comment by Kyriten** [comment] 2016-08-20 04:52
remove the quotes when putting it in the config.ini file
Example: `location = 48.179459, 11.547390`

**Comment by pyr0ball** [comment] 2016-08-20 07:21
For beehive you need to call out the location in each new python instance on your launch script.

See example: http://pastebin.com/Dna7JTMu

Configuration issue, not a bug. Closing. If you need additional support please come to the #help channel on discord. We're setting up a support forum for these kinds of posts which will be available soon™

**Closed by pyr0ball** 2016-08-20 07:21 UTC
