### ISSUE TITLE
Issue with new install

### ISSUE THREAD

**Issue by Bart274** [PokemonGoMap/PokemonGo-Map#90] opened 2016-08-08 08:16 UTC
I used the run the PGM from the first repo and it worked great.
Now I get these errors:
```
Exception in search_worker:
Traceback (most recent call last):
  File "C:\PGM\pogom\search.py", line 219, in search_worker_thread
    check_login(args, account, api, step_location)
  File "C:\PGM\pogom\search.py", line 266, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "c:\pokemongo-map\src\pgoapi\pgoapi\pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError
```

## Expected Behavior
I expect the worker to work and the map to display.

## Current Behavior
Nothing starts because of these errors

## Steps to Reproduce (for bugs)
1. use this config.ini file (personal data obscured):
```
auth-service:           ptc
username:               ***
password:               ***
location:               ***
gmaps-key:              ***
host:                   0.0.0.0
```
2. run command `runserver.py -st 5 -dc`

## Your Environment
* Version used: latest dev version
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by Bart274** [comment] 2016-08-08 08:17
it seems someone else made the same issue while I was creating mine: https://github.com/PokemonGoMap/PokemonGo-Map/issues/89

**Comment by Octylpy** [comment] 2016-08-08 08:28
Duplicate of #89

**Closed by Octylpy** 2016-08-08 08:28 UTC
Labels: duplicate
