### ISSUE TITLE
0 pokemon 0 pokestop 0 gym

### ISSUE THREAD

**Issue by jeremydevos** [PokemonGoMap/PokemonGo-Map#397] opened 2016-08-10 07:27 UTC
## Expected Behavior
2016-08-10 09:26:29,759 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 09:26:29,834 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 09:26:29,908 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 09:26:30,057 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 09:26:30,131 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 09:26:30,204 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 09:26:30,278 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 09:26:30,353 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 09:26:30,428 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 09:26:30,502 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

## Steps to Reproduce (for bugs)
Launch script python
1.
2.
3.
4.

## Context
develop

**Comment by Viper2k4** [comment] 2016-08-10 07:29
A bit more explanation plz :)

Did u have accept the ToS in the Game with our used account?

**Comment by jeremydevos** [comment] 2016-08-10 07:31
Yes everything worked there a few minutes ago but now nothing more

**Comment by blump** [comment] 2016-08-10 07:39
idem

**Comment by pposthoorn** [comment] 2016-08-10 07:42
I have the same issue. Looks like an IP ban. App on my phone also shows no Pokemon. When I switch to LTE it starts working again.

**Comment by blump** [comment] 2016-08-10 07:45
My ip is not ban. I checked

**Comment by pposthoorn** [comment] 2016-08-10 07:47
I get a response, it's just empty. Started about one hour ago.

**Comment by jeremydevos** [comment] 2016-08-10 07:48
@blump Did you check how?

**Comment by Viper2k4** [comment] 2016-08-10 07:53
oh i checked my map also (hosted on jelastic). I's also empty :/

**Comment by cichacz** [comment] 2016-08-10 07:58
It's completely fine on my machine. Using latest dev.
Here's my output from `pip list`:
```
alabaster (0.7.9)
argh (0.26.2)
Babel (2.3.4)
backports-abc (0.4)
certifi (2016.8.8)
click (6.6)
CommonMark (0.5.4)
ConfigArgParse (0.10.0)
docutils (0.12)
Flask (0.11.1)
Flask-CacheBust (1.0.0)
Flask-Compress (1.3.0)
Flask-Cors (2.1.2)
future (0.15.2)
geopy (1.11.0)
gpsoauth (0.3.0)
imagesize (0.7.1)
itsdangerous (0.24)
Jinja2 (2.8)
LatLon (1.0.1)
livereload (2.4.1)
MarkupSafe (0.23)
pathtools (0.1.2)
peewee (2.8.1)
pgoapi (1.1.6)
pip (8.1.2)
port-for (0.3.1)
protobuf (3.0.0)
protobuf-to-dict (0.1.0)
pycryptodomex (3.4.2)
Pygments (2.1.3)
PyMySQL (0.7.5)
pyproj (1.9.5.1)
pytz (2016.6.1)
PyYAML (3.11)
recommonmark (0.4.0)
requests (2.10.0)
s2sphere (0.2.4)
setuptools (25.1.6)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.4.5)
sphinx-autobuild (0.6.0)
sphinx-rtd-theme (0.1.9)
tornado (4.4.1)
watchdog (0.8.3)
Werkzeug (0.11.10)
wheel (0.29.0)
xxhash (0.6.1)
```

**Comment by Retalyx** [comment] 2016-08-10 08:03
I got the same problem, i tried to pull the last version , and now i can't install the flask_cache_bust module..

**Comment by cichacz** [comment] 2016-08-10 08:06
Tbh, i didn't run pip install after pulling newest version. It operates on what i had yesterday. That's why i included output from `pip list` so you can check if some lib is different eventually

**Comment by jeremydevos** [comment] 2016-08-10 08:08
alabaster (0.7.9)
argh (0.26.2)
Babel (2.3.4)
backports-abc (0.4)
certifi (2016.8.2)
click (6.6)
CommonMark (0.5.4)
ConfigArgParse (0.10.0)
docutils (0.12)
Flask (0.11.1)
Flask-CacheBust (1.0.0)
Flask-Compress (1.3.0)
Flask-Cors (2.1.2)
future (0.15.2)
geopy (1.11.0)
gpsoauth (0.3.0)
gyp (0.1)
imagesize (0.7.1)
itsdangerous (0.24)
Jinja2 (2.8)
LatLon (1.0.1)
livereload (2.4.1)
MarkupSafe (0.23)
pathtools (0.1.2)
peewee (2.8.1)
pgoapi (1.1.6, /root/PokemonGo-Map2/src/pgoapi)
pip (8.1.2)
port-for (0.3.1)
protobuf (3.0.0)
protobuf-to-dict (0.1.0)
pycryptodomex (3.4.2)
Pygments (2.1.3)
PyMySQL (0.7.5)
pyproj (1.9.5.1)
pytz (2016.6.1)
PyYAML (3.11)
recommonmark (0.4.0)
requests (2.10.0)
s2sphere (0.2.4)
setuptools (20.7.0)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.4.5)
sphinx-autobuild (0.6.0)
sphinx-rtd-theme (0.1.9)
tornado (4.4.1)
watchdog (0.8.3)
Werkzeug (0.11.10)
wheel (0.29.0)
xxhash (0.6.1)

Already the same error with pip install 
Cloning https://github.com/ChrisTM/Flask-CacheBust.git (to aa09ad861f104f987928fe9f5107ccfe0e4473c3) to /tmp/pip-build-wvTAhY/flask-cache-bust
  Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', assuming commit.
  Running setup.py (path:/tmp/pip-build-wvTAhY/flask-cache-bust/setup.py) egg_info for package flask-cache-bust produced metadata for project name flask-cachebust. Fix your #egg=flask-cache-bust fragments.

**Comment by blump** [comment] 2016-08-10 08:09
@jeremydevos Just by doing python runserver.py . 
On a banned Ip, here's the answer : 

`2016-08-10 10:02:44,914 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-10 10:02:45,042 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-10 10:02:45,211 [ search_worker_0][        search][ WARNING] Exception while downloading map: Seems your IP Address is banned or something else went badly wrong...
2016-08-10 10:02:45,214 [ search_worker_0][        search][   ERROR] Search step 1 area download failed, retrying request in 6.4 seconds`

**Comment by jeremydevos** [comment] 2016-08-10 08:10
Ok thank you @blump

**Comment by cichacz** [comment] 2016-08-10 08:14
@jeremydevos i have newer version of setuptools, and certifi, try to run pip with --upgrade option

**Comment by Jordan318** [comment] 2016-08-10 08:16
same error.

All of my scans (6) worked fine and when I have added one more scan (= +3 accounts) => 0 pokemon, 0 pokestop, 0 gyms on all scans

Every scans have 3 accounts. No ban IP error. I have tried to reboot the VPS.

**Comment by dthunder746** [comment] 2016-08-10 08:17
My jelastic server is also finding nothing, testing with the same accounts on a local install works just fine. I guess Niantic have done another ban wave.

**Comment by jeremydevos** [comment] 2016-08-10 08:30
@cichacz Result with --upgrade : 
Collecting **pgoapi** from git+https://github.com/keyphact/pgoapi.git@b4bf0e089dfe09903f8dda37dae56910e01f94cc#egg=pgoapi (from -r requirements.txt (line 18))
  Cloning https://github.com/keyphact/pgoapi.git (to b4bf0e089dfe09903f8dda37dae56910e01f94cc) to /tmp/pip-build-QiAPEk/pgoapi
  Could not find a tag or branch 'b4bf0e089dfe09903f8dda37dae56910e01f94cc', assuming commit.

Collecting f**lask_cache_bus**t from git+https://github.com/ChrisTM/Flask-CacheBust.git@aa09ad861f104f987928fe9f5107ccfe0e4473c3#egg=flask_cache_bust (from -r requirements.txt (line 25))
  Cloning https://github.com/ChrisTM/Flask-CacheBust.git (to aa09ad861f104f987928fe9f5107ccfe0e4473c3) to /tmp/pip-build-QiAPEk/flask-cache-bust
  Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', assuming commit.
  Running setup.py (path:/tmp/pip-build-QiAPEk/flask-cache-bust/setup.py) egg_info for package flask-cache-bust produced metadata for project name flask-cachebust. Fix your #egg=flask-cache-bust fragments.

**Comment by RavinLunatc** [comment] 2016-08-10 08:32
Same issue. Logging in through wifi on my phone shows zero stops, gyms, or mon, but switching to data they appear. Maybe some sort of request by IP limit/softban?

**Comment by cichacz** [comment] 2016-08-10 08:35
@jeremydevos it's just a warning, but doesn't break anything. I have it also and it's working normally.
Seems like this is caused by some IP bans..

**Comment by blump** [comment] 2016-08-10 08:36
Locally with an account that works. It is a kind of soft ban with the ip

**Comment by EmpowerZ** [comment] 2016-08-10 08:55
I have done some checking doesn't look like a plain IP ban.

Used the same IP and account to login from mobile and it worked (I could see and catch pokemons)!
And after doing that, magically, my tracker started working again. 

So I think Niantic might be checking for some packet which is send from the game, but not from the trackers. 
And if it is not sent for a while, server just won't respond.

**Comment by blump** [comment] 2016-08-10 08:56
@EmpowerZ 
I agree

**Comment by lungbubble** [comment] 2016-08-10 08:57
Just had same issue, all scanners stopped showing pokemon, no ban errors or anything.  Though seemed like a noticable delay on phone before pokemon showed up even in game on cellular data...maybe just a server issue?

**Comment by RavinLunatc** [comment] 2016-08-10 08:59
New IP, and I'm getting scan results again...

**Comment by lungbubble** [comment] 2016-08-10 09:01
If it is, wonder if its temporary, and if so, how temporary.

**Comment by drag0no** [comment] 2016-08-10 09:05
Any recommendations how to setup proxy on workers correctly? Well, btw, is it possible?

**Comment by Myxa767** [comment] 2016-08-10 09:07
Change nothing - everything works fine now. Maybe issue was on the their side?

**Comment by blump** [comment] 2016-08-10 09:08
Yes it's working again , but then it happened again

**Comment by drag0no** [comment] 2016-08-10 09:11
@blump , my conf is:
sd = 10
200 workers

I think the second thing is the reason...

**Comment by blump** [comment] 2016-08-10 09:14
Me 25 Workers . 

For the moment I test:
- ip: new
- workers : 5
- sd : 5

it works

**Comment by jeremydevos** [comment] 2016-08-10 09:17
Doing nothing it works again

**Comment by blump** [comment] 2016-08-10 09:18
@jeremydevos 
Yes but it has again 5 minutes later for me

**Comment by jeremydevos** [comment] 2016-08-10 09:22
@blump Yes it does not work :(

**Comment by blump** [comment] 2016-08-10 09:24
@jeremydevos your config ?

**Comment by MichalCerny** [comment] 2016-08-10 09:25
I have 20 workers and get 0 pokemons too. After 5 minute I put server off it works again. Maybe some IP request API limit?

**Comment by blump** [comment] 2016-08-10 09:26
@MichalCerny your sd in config ?

**Comment by MichalCerny** [comment] 2016-08-10 09:30
@blump default 5

**Comment by choell** [comment] 2016-08-10 09:45
My "solution" is the following:
Login into the official Pokemon Go App, catch a Pokemon with the worker, Logout. Restart Worker...

**Comment by RavinLunatc** [comment] 2016-08-10 09:49
Not connected to the new "You're moving too fast, click to confirm you're a passenger" thing they've added?

**Comment by blump** [comment] 2016-08-10 09:53
My test:
- Below 20 workers , it's work .
- When adding the 20 th worker , 1min 20 seconds after all my workers sent back 

`2016-08-10 11:53:01,430 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms`

**Comment by MichalCerny** [comment] 2016-08-10 09:53
Ok guys do you know about someone who selling accounts on lvl 1, that catches some pokemons a spins some pokestops? I don't have time for loggin in with workers and play some game. Thanks

**Comment by MichalCerny** [comment] 2016-08-10 09:54
@blump I have 22 workers exactly and it works for 25 minutes now without problem .. after 5 min server off

**Comment by blump** [comment] 2016-08-10 09:58
@MichalCerny 
Tell me if this still works at home in 15 minutes please

**Comment by Cammo009** [comment] 2016-08-10 09:59
I have 13 workers. Was working 1 hour ago and now having the same issue. ) results for Gym's, Pokestops,  Pokemon. 

Tried another account and didn't work.

**Comment by Arthok** [comment] 2016-08-10 10:04
I have the same issue on a private server with one worker and st5 - sd10.
I think it's a soft ban

**Comment by Cammo009** [comment] 2016-08-10 10:05
how can it be a soft ban if it still working on pokemon go?

**Comment by Arthok** [comment] 2016-08-10 10:06
Because the IP where I play, isn't the same that my server who runs Pokemap

**Comment by LcTrKiD** [comment] 2016-08-10 10:07
Same here... I reboot the server and try with only one worker...

**Comment by Arthok** [comment] 2016-08-10 10:08
It's working with another IP and same accounts for me so the soft ban seems logic to me

**Comment by Cammo009** [comment] 2016-08-10 10:08
If this is the case of the IP ban. How can they developers get around this?

**Comment by Arthok** [comment] 2016-08-10 10:09
VPN, Proxys ... It begins to get harder to run a map :)

**Comment by Cammo009** [comment] 2016-08-10 10:09
Do you mean stop the server or shutdown the VPS/Computer and start again?

**Comment by MichalCerny** [comment] 2016-08-10 10:09
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3217#issuecomment-238486087

**Comment by MichalCerny** [comment] 2016-08-10 10:36
@blump it works now for a hour without problem it looks like some dates throttled based on pokemon go usage.

**Comment by Cammo009** [comment] 2016-08-10 10:39
I now using 1 user and its now still now working yet if soft ban ip is the cause.

**Comment by Toetje585** [comment] 2016-08-10 12:00
Same here, banned my IP!

**Comment by Viper2k4** [comment] 2016-08-10 12:13
jelastic is back again (also got an mail that THEY fixed it)^^

**Comment by chuyskywalker** [comment] 2016-08-10 14:55
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Closed by chuyskywalker** 2016-08-10 14:55 UTC

**Comment by lungbubble** [comment] 2016-08-10 15:56
chuyskyswalker, I mean no offense, but I'm very curious about devs saying "this is not a support forum" and other reasons for closing issues I just don't get.  1, it seems as though that's splitting hairs in a way I, and I don't think others understand (seems as though "support" is a valid description for this forum).  2, what's wrong with people helping each other out on a similar issue (in the hopes of dwindling it down to its nitty gritty components to see if it is something developers can help with or not)?.  3, how does it hurt this forum to have this discussion here to the point at which it should be closed?  4.  why would these things motivate someone to close it out when that person(s) simply don't have to take part in the discussion and therefore have no obligation thereto?
