### ISSUE TITLE
[Feature Request] Captcha Solving in-map

### ISSUE THREAD

**Issue by thatsweater** [PokemonGoMap/PokemonGo-Map#1478] opened 2016-10-06 19:05 UTC
## Expected Behavior
With account recycling for empty accounts, accounts are put into a queue because they are turning up 0/0/0 for each scan. This is a good start, but accounts still become useless. It would be ideal then for captchas to be solved in-map, allowing for the communities that use maps to help maintain accounts.

The idea behind this is, say i am currently losing 10 accounts per hour and have ~5 users connect to the map per hour, they could each be prompted to solve a couple of captchas to put those accounts back into the rotation.

## Current Behavior
At first glance it may appear not-possible, as accounts that have the captcha solved do not last as long as fresh accounts; but with coming anti-detection measures (speed limits, perhaps pathing), accounts should be less detectable.

## Possible Solution
I wish i had more to offer in terms of implementation, only the wish that this could be possible. 

## Context
The recent update causing accounts to return 0/0/0 unless captchas are entered.

Thank you all for your hard work.

**Comment by klvs** [comment] 2016-10-06 21:47
So this isn't a free solution, but it is very inexpensive. It could be done in the same way that https://github.com/sriyegna/Pikaptcha uses 2captcha to solve captchas for account creation. I personally don't have the time or know how to make this work at the moment but will look into it if someone doesn't beat me to it.

**Comment by BaIthamel** [comment] 2016-10-06 23:03
Pretty much a duplicate of #1470

**Closed by BaIthamel** 2016-10-06 23:03 UTC
Labels: duplicate

**Comment by moggd** [comment] 2016-10-06 23:31
@klvs Why would you want to set that up for recaptchas when you could just create 10000's of accounts to begin with and just have them queue'd through?

**Comment by SkOODaT** [comment] 2016-10-06 23:44
@moggd eventually your queue would run out and making new accounts isnt going to solve our issue all its going to do is cause the pokemon company to lock thier account creation down even more......

**Comment by klvs** [comment] 2016-10-06 23:54
@moggd that is sort of a solution. However, that script works with Phantom.js and needs to load an entire chrome instance. i.e it's very heavy weight and requires a lot of resources. As @SkOODaT said it may also prompt them to lock down account creation. 

If you're running a large enough map, just queuing and creating accounts isn't very feasible unless you're willing to shell out for more servers to generate accounts. Not to mention that if newer accounts were put under more scrutiny and captcha'd more frequently  that solution will all together fail for even smaller maps.

**Comment by FlarumHostingCo** [comment] 2016-10-07 00:58
I am noticing when I get the 1st captcha for a worker, it just received to 10km walking award shortly before.  I wonder if 10km award is a trigger.

**Comment by klvs** [comment] 2016-10-07 01:16
@FlarumHostingCo Ah, it could be a distance trigger. Good point. Someone on reddit noticed that slowing their scans seemed to prevent it. Could be just that it delayed the captcha if distance traveled is a trigger.

**Comment by klvs** [comment] 2016-10-07 01:17
As a side note, if that's the case, account burn rate is easily predictable based on scan speed.

**Comment by articlefr** [comment] 2017-01-11 14:39
You can also use CaptchaSolutions https://www.captchasolutions.com/ to automatically solve captchas and Google's (I'm not a robot) captcha.
