### ISSUE TITLE
Map is dropping scans / Map has holes

### ISSUE THREAD

**Issue by vervsdvgwegfeg** [PokemonGoMap/PokemonGo-Map#519] opened 2016-08-11 20:06 UTC
When I run pokemon go map I sometimes get this gaps:

![untitled1](https://cloud.githubusercontent.com/assets/20638796/17603056/b4f67eb0-600f-11e6-86af-017233aa9b29.png)

others are usually larger....

**Comment by rbryson74** [comment] 2016-08-11 20:10
Do they stay empty until the next scan pass or to they fill in on the next refresh?

**Comment by ovkhan** [comment] 2016-08-11 20:17
Always empty

**Comment by DoktorJ** [comment] 2016-08-11 20:18
I've seen holes on mine before, but they usually seem to fill in (or sometimes move to a different spot) on the next pass

**Comment by vervsdvgwegfeg** [comment] 2016-08-11 20:19
@rybryson74 

they fill in

**Comment by imynwulf** [comment] 2016-08-11 20:34
@rbryson74 I've seen these as well. 
I took screenshots for 3 updates in a row that demonstrate the issue.

http://i.imgur.com/anPj183.png 
http://i.imgur.com/yUvfFxG.png
http://i.imgur.com/LHJyGbT.png

There aren't any messages in the logs during those scans.

**Comment by rbryson74** [comment] 2016-08-11 20:35
ah yes. the dreaded worm gap. I think it happens when a few threads set the scan location just out of sync of when the web server pulls the data for the map. This causes a lag. It should fill out and reset when the next scan pass starts.

**Comment by vervsdvgwegfeg** [comment] 2016-08-11 20:36
@rbryson74 it happens every scan...

**Comment by rbryson74** [comment] 2016-08-11 20:38
Well, as far as I can tell it is only a visual bug. the scans should still be occurring.

**Comment by imynwulf** [comment] 2016-08-11 20:48
In my case, the gap is well behind the current scan. The issue never bothered me enough to raise an issue report on it.

**Comment by invisiblek** [comment] 2016-08-12 03:33
This is typically due to an account not being activated or ToS not accepted for it

**Comment by DoktorJ** [comment] 2016-08-12 04:43
@invisiblek I don't think so; these holes occur within a single worker's scan, even when that worker is using only a single user account. If it were due to the account not being activated or not having accepted the ToS, the worker's entire scan area would be empty.

**Comment by HelkaPL** [comment] 2016-08-12 07:06
Well, i got similar empyt fields, but my sell show someting like that...
![przechwytywanie](https://cloud.githubusercontent.com/assets/20984502/17615099/0079c930-606c-11e6-8610-bc4101f1c111.PNG)

**Comment by teknicsrx7** [comment] 2016-08-12 11:35
I actually have it occur more or less depending on location my hive is -lp 4 with 2 accounts per worker. I put the hive over one town, rarely get "step xx area download failed" (which leads to holes in my scan). Move the hive 1 town over after leaving it offline for a bit, and I get repeated "step xx area download failed" on random accounts leaving holes all over. Haven't explored it deeper

**Comment by AddisonG** [comment] 2016-08-13 13:04
This constantly happens with me - But **only in Firefox**. I notice that its also always when the circles are a certain color. It's almost like Firefox just isn't able to render them when they're a certain color.

I checked the net traffic, and there was nothing unusual/malformed about the request or response, at a glance.

**Comment by cirespieler** [comment] 2016-08-16 08:11
@HelkaPL looks like some of your workers have been banned. Happened to two of mine earlier today. Remove/replace them and you'll be fine.

**Comment by pyr0ball** [comment] 2016-08-20 08:20
account or config issue, not a bug. Closing

**Closed by pyr0ball** 2016-08-20 08:20 UTC
Labels: issues are not for support!, not a bug - server issue

**Comment by AddisonG** [comment] 2016-08-20 16:37
@pyr0ball
I strongly suspect this is an issue separate from accounts or configuration, and have several pieces of evidence here which prove it. That said, I respect your decision to close this due to some of the more off-topic discussion involving banned accounts.

**1)** The behaviour is exhibited on every area that has been successfully scanned, approximately 350 seconds after it has been scanned.

_Therefore, there is no possible way that it could be an issue with scanning the area. After all, it has already been scanned - I can see a different area of the map being updated._

**2)** I left Chrome and Firefox open, and about 5 minutes later, they both started doing this (at the same time), with the exact same areas. Refreshing the page stopped the issue in the browser that was refreshed, but not the other one.

Additionally, there is nothing unusual even in the debug logs, and the network traffic appears to be consistent.

_Therefore, there is no way this could be a problem with a PTC account. Besides, this happens after the area has been scanned, not as a result of a bad scan._

**3)** My server is configured without anything fancy, and all config options are default where possible.
`runserver.py -a ptc -u username -p password -l "-23.456 123.456" -st 10`
I'm accessing it through localhost, and haven't changed any files from master.

**4)** I installed everything fresh, and changed no options/config for any programs. This includes:
Node.js 6.31
Python 2.7.12
Microsoft Visual C++ Compiler for Python 2.7
Chrome (Yes! Completely stock, no addons, no plugins, nothing)

I always make sure to re-build everything when I git pull, though this has happened to me since the day I got it (2 weeks ago)

_Therefore, it is highly unlikely that this is an issue with configuration or settings, as even with everything vanilla, it still happens._
