### ISSUE TITLE
The map is not showing pokemon. What else should be included?

### ISSUE THREAD

**Issue by So1omon36** [PokemonGoMap/PokemonGo-Map#849] opened 2016-08-19 16:35 UTC
The map is not showing pokemon. What else should be included?
![map](https://cloud.githubusercontent.com/assets/21090554/17816868/0ef55c76-6644-11e6-9d92-c62dce29d925.jpg)

my config 
`# Authentication settings
auth-service: google
username: login my
password: pass

# Database settings
#db-type: mysql
#db-host: locallhost
#db-name: admin_map
#db-user: admin_umap
#db-pass: pass
#db-port: 3306

# Search settings
location:22.269081755237067 114.13833618164062
no-gyms: true             # disables gym scanning (default false)
no-pokemon: true          # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#scan-delay:            # default 10
#step-limit:            # default 12

# Misc
gmaps-key:  my key            # your Google Maps API key
#proxy:                 # Proxy URL e.g. socks5://127.0.0.1:9050
#webhook:               # webhook URL (including http://)
#webhook-updates-only:               # only send updates to webhooks, (excludes gyms & non-lured pokéstops)

# Webserver settings
host:  my host                  # address to listen on (default 127.0.0.1)
port:5000                  # port to listen on (default 5000)
locale:ru                # pokemon translation
#ssl-certificate:       # path to ssl certificate
#ssl-privatekey:        # path to ssl private key

#Uncomment a line when you want to change its default value (Remove # at the beginning)
#username, password, location and gmaps-key are required`

**Comment by Becold** [comment] 2016-08-19 16:39
The error come frome : 
`location:22.269081755237067 114.13833618164062`
--->
`location: '22.269081755237067, 114.13833618164062'`

and change that too : 
`no-gyms: true # disables gym scanning (default false)`
`no-pokemon: true`
---->
`#no-gyms: # disables gym scanning (default false)`
`#no-pokemon: #disables pokemons scanning (default false)`

**Comment by So1omon36** [comment] 2016-08-19 16:48
It did not help. The map starts with the team, but the pokémon do not appear.

**Comment by So1omon36** [comment] 2016-08-19 17:04
`SSLError: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2016-08-19 13:01:18,195 [ search-worker-0][        search][    INFO] Search step 1 beginning (queue size is 18)
2016-08-19 13:01:18,195 [ search-worker-0][   auth_google][    INFO] Google User Login for: MyAccount@gmail.com
2016-08-19 13:01:18,222 [ search-worker-0][        search][   ERROR] Exception in search_worker: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed. Username: usernameMyaccount@gmail.com
Traceback (most recent call last):
  File "/home/admin/web/mysite.ru/public_html/pogom/search.py", line 452, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/home/admin/web/mysite.ru/public_html/pogom/search.py", line 602, in check_login
    api.set_authentication(provider=account['auth_service'], username=account['username'], password=account['password'])
  File "/usr/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 92, in set_authentication
    self._auth_provider.user_login(username, password)
  File "/usr/local/lib/python2.7/site-packages/pgoapi/auth_google.py", line 58, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "/usr/local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/usr/local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
`

**Comment by angrymoose** [comment] 2016-08-19 17:38
Does no one read the default message when creating an issue. 

> ISSUES ARE NOT FOR SUPPORT!!!
> Join discord (channel: #help) for support at this link: https://discord.gg/PWp2bAm

A quick glance at your error logs makes it clear that you are unable to verify the ssl certificate from google. As you are unable to login to your account because you can not autheticate the ssl cert results in catastrophic error. Again this is not a bug in the code but rather with your infrastructure.

**Comment by pyr0ball** [comment] 2016-08-19 17:59
Closing. Not a bug.

**Closed by pyr0ball** 2016-08-19 17:59 UTC
