### ISSUE TITLE
[ WARNING] Exception

### ISSUE THREAD

**Issue by vinsilsim** [PokemonGoMap/PokemonGo-Map#865] opened 2016-08-20 01:51 UTC
2016-08-19 23:08:47,151 [ search-worker-0][        search][ WARNING] Exception while downloading map: 'NoneType' object is not iterable
2016-08-19 23:08:47,151 [ search-worker-0][        search][   ERROR] Search step 1 area download failed, retrying request in 10 seconds

anyone know why?

**Comment by pyr0ball** [comment] 2016-08-20 06:43
Not a bug, server overload or config issue. closing

**Closed by pyr0ball** 2016-08-20 06:43 UTC

**Comment by vinsilsim** [comment] 2016-08-20 12:27
@pyr0ball how if i donwload lastest version and run with default configs?
