### ISSUE TITLE
Exceeded Max Connections (Flask)

### ISSUE THREAD

**Issue by SimonTellsAll** [PokemonGoMap/PokemonGo-Map#305] opened 2016-08-09 14:16 UTC
## Expected Behavior
The application to run smoothly.

## Current Behavior
I run a server for my local area that a fair amount of people have access to. I frequently experience an exception error in the python window (Although this doesn't stop the scan - it may have an impact on the page displaying to end-user). It is due to "Max connections exceeded" in flask.

## Possible Solution
Not entirely sure

## Steps to Reproduce (for bugs)
1. Run a server.
2. Have 30+ users active on it at once
3. Error will constantly output in python window

## Context
The application may fail to continue to run or crash alltogether because of the frequent exceeding maximum connections. (This error appears maybe every 5-10s) the search continues fine though.

## Your Environment
* Version used: Dev
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by imynwulf** [comment] 2016-08-09 14:45
Are you using SQLite or MySQL?

**Comment by invisiblek** [comment] 2016-08-09 14:55
https://github.com/PokemonGoMap/PokemonGo-Map/pull/239 doesn't fix MySQL, https://github.com/PokemonGoMap/PokemonGo-Map/pull/296 is the magic bullet i think/hope/pray

**Comment by invisiblek** [comment] 2016-08-09 14:56
but yea, this is a dupe of https://github.com/PokemonGoMap/PokemonGo-Map/issues/71

**Closed by invisiblek** 2016-08-09 14:56 UTC
Labels: duplicate

**Comment by marumari** [comment] 2016-08-09 14:58
@invisiblek Err, is this a dupe?  I think they may be running up against limitations of Flask (and therefore should use something like uWSGI) and not MySQL concurrency issues.

**Comment by SimonTellsAll** [comment] 2016-08-09 15:00
I use a mysql database to handle the database side of things. It may be the limitations of f;ask @marumari as you said. Is there anyway around thing?

**Comment by marumari** [comment] 2016-08-09 15:06
Oh, if that's the case, then it probably is a duplicate of the other bug.  :)
