### ISSUE TITLE
KeyError: 'map_cells'

### ISSUE THREAD

**Issue by K4PDaddy** [PokemonGoMap/PokemonGo-Map#854] opened 2016-08-19 19:23 UTC
## Current Behavior

2016-08-19 15:12:18,251 [ search-worker-0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds. Username: XXXXXXXXXXXXXXX@gmail.com
Traceback (most recent call last):
  File "/home/XXXX/PokemonGo-Map/pogom/search.py", line 468, in search_worker_thread
    findCount = parse_map(args, response_dict, step_location, dbq, whq)
  File "/home/XXXX/PokemonGo-Map/pogom/models.py", line 383, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

## Possible Solution
The JSON Keys just need to be updated in models.py.
My assumption is that the API changed the keys in the return data. I don't know what the return data contains, so I don't want to just willy-nilly change keys around.

Just thought you all ought to know.

## Your Environment

* Version used: 9322e04
* OS: Ubuntu 16.04

**Comment by Wegi** [comment] 2016-08-19 20:18
This seems to occur if the account is either not activated or banned. Probably either the account is banned or your IP banned if you get it for every account.

**Comment by straitpick** [comment] 2016-08-19 20:40
I'm also having this the last 2 hours or so, was working fine, shut down server, restarted and i get this error constantly, i've tried multiple accounts same error, yet i can log into them via iPhone and iPad

**Comment by jccwright** [comment] 2016-08-19 21:12
@straitpick, you may be able to log in but are you able to capture pokemon,
or do they all flee. Can you search a pokestop? Do any pokemon even show up
for you? Those are also signs of soft bans.

**Comment by Azryyal** [comment] 2016-08-19 22:11
I get this same error. When I log in via the PoGo app, I get this:

"Our servers are humbled by your incredible response.

We are working to resolve the issue. Please try again soon!"

So, not hard banned? Not soft banned? Just ptc access down temporarily?

**Comment by pyr0ball** [comment] 2016-08-20 07:25
Not a bug, you've got a bad account. Closing

**Closed by pyr0ball** 2016-08-20 07:25 UTC
Labels: issues are not for support!, not a bug - server issue

**Comment by creatingwake** [comment] 2016-08-20 09:32
FYI - this error is not due to bad account.  I had same issue with two brand new accounts.  The issue was resolved by using one of the accounts to log into the actual game, complete the initial tutorial and catch first pokemon.  After that, account works fine.  

The login account needs to be activated by logging into the game client it seems.

**Comment by elvquant** [comment] 2016-08-23 05:25
All Accounts I using are activated by initial tutorial. Get the error overnight, ptc accounts and google Account (not used for scanning several day). Seems a bann of ip, but I not. My playing account works well I original Niantic app from same ip...
