### ISSUE TITLE
Spawn Point Dead Zone

### ISSUE THREAD

**Issue by chriskellydev** [PokemonGoMap/PokemonGo-Map#947] opened 2016-08-23 01:48 UTC
## Expected Behavior
Exported spawns.json file from --dump-spawnpoints should allow all spawn points to be scanned.

## Current Behavior
Some exported spawn points from pogom.db seem to not be exported (and are not within range/time of other spawns). Might have something to do with the compression mentioned in https://github.com/PokemonGoMap/PokemonGo-Map/issues/939

## Steps to Reproduce (for bugs)

So here's my map area of interest. The numbers are the minute times for the individual spawns.

![image](https://cloud.githubusercontent.com/assets/4634288/17876952/e90761ba-68ac-11e6-8cca-1e0daa1f3691.png)

**The 41 by the river is actually 56, duplicated my labels**

The spawn point of interest is the one that spawns at 39 minutes on the hour. The spawn point is in my pogom.db database (obviously) and I have two entries from when I was running my initial beehive:

![image](https://cloud.githubusercontent.com/assets/4634288/17877006/7a50547e-68ad-11e6-9f2f-a93ed092dd65.png)

However, when dumping spawn points, that one in particular never gets dumped out and thus never gets scanned (since nothing else is nearby with a timer after 39 minutes but within 70m). The closest would be that 41 minute point but according to my Google maps estimate it is ~74m.

And just for a little bit more information, here is what happens to the spawn points in that clump:
* 8 minute: dumped
* 12 minute: dumped
* 13 minute: dumped
* 35 minute: dumped
* 39 minute: excluded
* 41 minute (actual one): excluded

## Context
The only reason I noticed this was because an Electrode spawned at the upper 34 minute point. By the time I got there a Charmander appeared nearby (at the 39 minute point in question). I found the Charmander before it showed on my map and expected to see it show up later (though made a mental note just in case). It actually never showed up and and my pogom.db does not have a Charmander entry for that location. I then noticed that outside of beehive scans, that Spawnpoint ID has no entries at all and is thus a dead zone.

## Your Environment
* Fedora 24 Server
* Python 2.7
* Commit: fdcdfe76cae9a2023200ab933f8e4fff4088abc8 (most recent)

## Final
If a dev really wants my spawns.json/pogom.db to look at these distances/times/exports just let me know.

**Comment by justsomedudeonthenet** [comment] 2016-08-23 03:21
Spawnpoint compression hasn't made it into develop yet.  So it's not that.
I wouldn't mind looking at your pogom.db and spawns.json files if you can post them somewhere.

**Comment by justsomedudeonthenet** [comment] 2016-08-23 03:24
Increase your -st by a couple and see if that spawnpoint gets included.

**Comment by chriskellydev** [comment] 2016-08-23 13:25
Just some more information:

* Initial beehive scan was -st 13
* Export to spawns.json was done with -st 20 (though the points in question are no where close to the edge of even -st 10).
* There are 553 unique Spawn IDs in my pogom.db
  * Initial -st 13 beehive was run with enough accounts to complete a full scan in ~7 minutes.
  * Initial beehive was run for 2-3 hours.
    * This would indicate that dead zone spawns should have no more than 3 entries.
* There are 393 instances of the tag "spawnpoint_id" in the spawns.json file.
* Spawn ID for the 39 minute spawn is: 89c23467403
  * Only has 3 entries (3rd one appeared overnight but you can see from the disappear time that there was a significant gap before it and the other 2 are the beehive entries).
  * Compared to say 89c234426e1 which has 7 that are all nicely spaced in hourly intervals.

Attached zip contains pogom.db and the spawns.json generated from a -st 20 --dump-spawnpoints run.

[deadzone.zip](https://github.com/PokemonGoMap/PokemonGo-Map/files/432486/deadzone.zip)

**Comment by averylarry** [comment] 2016-08-23 18:10
Does MonjoNL's fix from #939 address this?

**Comment by chriskellydev** [comment] 2016-08-23 22:34
That seems to do it. The outputted spawns.json now has significantly more data in it including the 39 minute spawn point:

```
{... "spawnpoint_id": "89c23467403", "time": 2351}
```

I'm going to leave the issue open until someone commits the fix but consider this resolved once MonjoNL's models.py fix from #939 's comments is tested/committed.

**Comment by BaIthamel** [comment] 2016-08-24 19:47
Conna call this a duplicate of #939 then for now.

**Closed by BaIthamel** 2016-08-24 19:47 UTC
Labels: duplicate
