### ISSUE TITLE
SS does not scan a spot if it fails at first

### ISSUE THREAD

**Issue by Slivo-fr** [PokemonGoMap/PokemonGo-Map#1174] opened 2016-09-06 10:31 UTC
If the worker that was meant to scan a spot fail, the post isn't scanned at all.

## Expected Behavior
A spawn should always be scanned

## Current Behavior
I often experience error like 
`2016-09-06 12:09:43,727 [ search-worker-8][        pgoapi][   ERROR] Request for new Access Token failed! Logged out...`
`2016-09-06 12:09:43,727 [ search-worker-8][        search][   ERROR] Invalid response at 43.614119,3.916817, abandoning location`
The spot remain unscanned and the pokemon isn't displayed.

## Possible Solution
Scan the spot with another worker after a short delay if it failed.

**Comment by justsomedudeonthenet** [comment] 2016-09-06 21:29
Duplicate of #1181

**Closed by justsomedudeonthenet** 2016-09-06 21:29 UTC
