### ISSUE TITLE
[Feature Request] Accounts stored in DB

### ISSUE THREAD

**Issue by Sempra90** [PokemonGoMap/PokemonGo-Map#1176] opened 2016-09-06 12:20 UTC
Ist not an Issue its an Idea for Devs.

Handle all created PTC Accounts in DB.

First  instance starts with (10) workers, first 10 accounts pulled from db and set them to "in use" and start scanning, if one account blocked or someting elese went wrong, write to db "blocked" or "cooldown until xx:xx:xx".
start a second Server he pulls another 10 accounts from db, but only if there is no "in use" or "blocked" sign and start to scan too.

New Accounts can be set in Statuspage.

**Comment by azd2** [comment] 2016-09-06 14:48
It's already done in this PR: #1037

**Comment by azd2** [comment] 2016-09-06 14:50
Is this okay by the way? Pointing ppl who want a feature to a PR where it's implemented? Not sure...

**Comment by jchristi** [comment] 2016-09-06 14:54
@azd2 I think so. It should point them to where dev is working on the issue so that they don't go try to implement it themselves causing duplicated effort :)

**Comment by Sempra90** [comment] 2016-09-06 15:37
But the Accounts only stored in a csv file, Not in db. And for each Instance you Need a seperate csv file .

**Comment by n3cr0cr0w** [comment] 2016-09-06 15:51
#1037 Has not been pulled in to the main code base yet. Plus it has not been updated in a few days.

**Comment by jchristi** [comment] 2016-09-06 16:26
If a PR already exists for solving an issue, then post in the PR instead of creating a new issue resulting in more noise and paperwork that wastes maintainer and developer time sifting through.

**Comment by KoffeinKaio** [comment] 2016-09-06 21:22
Werent there two pull requests but only one got implemented in the repo?
I think those two are different approaches and would conflict, so this issue wont be solved with the mentioned PR

also: I second this, need! I run 4 processes with 5-30 workers, a databse where they could pull accounts from would save me a lot of file handling.

**Comment by justsomedudeonthenet** [comment] 2016-09-06 22:07
Closing as duplicate of #1147

**Closed by justsomedudeonthenet** 2016-09-06 22:07 UTC
Labels: feature request
