### ISSUE TITLE
Error - something strange happened

### ISSUE THREAD

**Issue by marcmicalizzi** [PokemonGoMap/PokemonGo-Map#190] opened 2016-08-08 18:35 UTC
Running into the following when running the map in the past little bit:

2016-08-08 18:34:13,575 [ search_worker_1][       rpc_api][    INFO] Error - something strange happend...
2016-08-08 18:34:13,576 [ search_worker_1][        search][ WARNING] Exception while downloading map: list index out of range
2016-08-08 18:34:13,576 [ search_worker_1][        search][   ERROR] Search step 6 area download failed, retrying request in 30 seconds
2016-08-08 18:34:17,113 [ search_worker_2][        search][   ERROR] Search step 3 map parsing failed, retrying request in 50 seconds
Traceback (most recent call last):
  File "/[removed]/PokemonGo-Map/pogom/search.py", line 242, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/[removed]/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by forsakenzombi** [comment] 2016-08-08 18:40
same issue

**Comment by alachmann** [comment] 2016-08-08 18:42
same

**Comment by marumari** [comment] 2016-08-08 18:52
This is likely a duplicate of #189.

**Closed** 2016-08-08 19:14 UTC
Labels: duplicate
