### ISSUE TITLE
Pokemon detected at wrong date, thus not showing up on map

### ISSUE THREAD

**Issue by DrAtari** [PokemonGoMap/PokemonGo-Map#318] opened 2016-08-09 16:06 UTC
Sometimes Pokemon are detected at the wrong date. Today is 9th of August 2016, but a Squirtle and over 50 other Pokemon are stored in the database as having appeared on July 18th 2016. 

While the Pokemon are visible on the Stats page, they are not visible on the live map.

Date stored in the database is always 2016-07-18 21:53:35.231000

**Comment by simarsenault** [comment] 2016-08-09 16:31
Duplicate of #142.

**Closed** 2016-08-09 18:23 UTC
Labels: duplicate
