### ISSUE TITLE
Not able to interact with the map when accessin through Android

### ISSUE THREAD

**Issue by gatomiaurex** [PokemonGoMap/PokemonGo-Map#869] opened 2016-08-20 04:53 UTC
## Current Behavior

When I am browsing the map on my phone I am not able to interact with the map, pokemons, pokestops or the pin.

## Expected Behavior

I should be able to click the pokemons to see their timers, move the pin to change locations, interact with the map to move the map around.

## Steps to Reproduce (for bugs)

1.- Run runserver.py
2.- Access the map through my phone
3.- Try to interact with the map
4.- It won't let you click on things or change the part of the map you are in.

## Context

I am trying to use this map to see pokemons around me and to look for pokemons when I am outside.

## Your Environment
Windows 7 x64
Python 2.7

**Comment by Studio-XP** [comment] 2016-08-20 06:55
Old bug, pull request waiting for a second ok for it to be committed. #623.

**Comment by angrymoose** [comment] 2016-08-20 21:01
To move the map on mobile go to options click location settings switch lock marker off. It's an annoying feature that was added so you don't accidentally move the pin. It's quite useful but it can cause issues if you don't know its there. I keep it on unless I need to move the pin then I lock it again, helps prevent getting bots banned as you move around the area.

**Comment by pyr0ball** [comment] 2016-08-21 04:40
not a bug, closing

**Closed by pyr0ball** 2016-08-21 04:40 UTC
Labels: not a bug - server issue

**Comment by Studio-XP** [comment] 2016-08-21 05:07
I'm not so sure it's what moose is saying.  "I should be able to click the pokemons to see their timers" gives me the impression that the page is crashing on him. The lock marker option keeps the marker in it's original location and doesn't prevent the map itself from being able to move around. As it stands, the page crashes on Android because of a critical javascript error, not allowing any interaction with it after then.
