### ISSUE TITLE
Exceeded maximum connections.

### ISSUE THREAD

**Issue by Cronick** [PokemonGoMap/PokemonGo-Map#94] opened 2016-08-08 08:53 UTC
## Expected Behavior
Well, it should not result in a 500 internal server error and give me the requested file.
This is by using a script for running the webserver only, and then I have a script for the scanners.

>[2016-08-08 10:44:27,527] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/dist-packages/playhouse/flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.

> 2016-08-08 10:44:27,527 [    Thread-11337][           app][   ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/dist-packages/playhouse/flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.

## Current Behavior
I get this error as I browse around the map, and it results in 500 internal server error, so the map is unstable and result in not updating as frequent as normal.

## Steps to Reproduce (for bugs)

I think it has something to do with the amount of workers, but i'm not 100% sure.

1. Run latest version (3.0.0)
2. Have multiple scanners on a given location.

## Context
As it gives me 500 internal server error, it makes it hard to navigate around the site without having to refresh the page a few times because it gives an 500 internal server error to maybe a javascript file, or loading a picture of a pokemon for the map.

## Your Environment

* Version used: 3.0.0
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Debian 8.0

**Comment by JZ6** [comment] 2016-08-08 08:54
duplicate of #71

**Closed by JZ6** 2016-08-08 08:54 UTC

**Comment by vrgomes** [comment] 2016-08-25 23:31
This error is related to Flask when there are many connections and has nothing to do with database.
Still happening is the latest builds.
Anyone has a fix for this?

**Comment by edgarborja** [comment] 2016-08-26 13:49
I think I found a solution, you should set --db-max_connections in the server thread as well, I was using it only for the workers, but it was the server causing the errors. 

I set --db-max_connections roughly to (max number of active visitors /2) and it seems to be stable now.
