### ISSUE TITLE
Can't type on "hide pokemon" box on iOS

### ISSUE THREAD

**Issue by leolobato** [PokemonGoMap/PokemonGo-Map#1194] opened 2016-09-07 09:39 UTC
## Expected Behavior

When tapping on the "Hide Pokémon" box, to be able to type on the on-screen keyboard.

## Current Behavior

The screen will scroll up and down very quickly (as if the keyboard was about to appear), the pokémon picker will be visible, the cursor will be blinking, but there's no keyboard to type on.

## Steps to Reproduce (for bugs)
1. Open the map on iOS Safari
2. Tap on the Gear icon for options
3. Open "Marker Settings"
4. Tap on the box under "Hide Pokémon"

## Context

Although we can still add pokémons to be filtered by picking them from the list, it would be much faster to be able to type.

## Your Environment

* Version used: Latest revision on develop (e92fa83), but it has been happening for a few days.
* Operating System and version (desktop or mobile): Latest iOS. Affects both Safari and Chrome

**Comment by DiscoTim** [comment] 2016-09-07 10:46
https://github.com/PokemonGoMap/PokemonGo-Map/issues/1133

**Comment by justsomedudeonthenet** [comment] 2016-09-07 13:38
Closing as duplicate of #1133

**Closed by justsomedudeonthenet** 2016-09-07 13:38 UTC
