### ISSUE TITLE
Lured pokes not showing on map (lure information is accurate)

### ISSUE THREAD

**Issue by LordRad** [PokemonGoMap/PokemonGo-Map#370] opened 2016-08-10 00:18 UTC
## Expected Behavior
Lured poke should be shown on map with timer

## Current Behavior
Lured poke is not being shown
![image](https://cloud.githubusercontent.com/assets/20796412/17537786/177c0804-5e65-11e6-9312-961afa75b1b9.png)

## Steps to Reproduce (for bugs)
Using develop version DLed 09/08/2016 (D/M/Y) at around 1pm GMT -5

1. reqs installed with no issues
2. npm installed no issues

## Your Environment
Python 2.7; 
pip --version
pip 8.1.2 from c:\python27\lib\site-packages (python 2.7)

node --version
v4.4.7

npm --version
2.15.8
* Operating System and version (desktop or mobile):
Win 7 Enterprise X86
localhost running with Chrome Versión 51.0.2704.103 m

On a side note I'm unable to git pull to update, Im getting: fatal: Not a git repository (or any of the parent directories): .git

**Comment by imynwulf** [comment] 2016-08-10 00:52
Sounds like a duplicate of #131.

**Comment by LordRad** [comment] 2016-08-10 01:55
Indeed looks like duplicate, any hints on the git pull thingie, kinda tired of re dling each time

**Comment by chuyskywalker** [comment] 2016-08-10 02:19
Please confirm that you are on the latest develop commit, until then...

**Closed by chuyskywalker** 2016-08-10 02:19 UTC
