### ISSUE TITLE
Searching is slow when using multiple accounts.

### ISSUE THREAD

**Issue by RollTideDG** [PokemonGoMap/PokemonGo-Map#321] opened 2016-08-09 17:16 UTC
## Expected Behavior
There is a noticeable delay between initiation of the scan and upserting of the records.

## Current Behavior
The first time through the loop of worker threads it seems to work alright. As it progresses through the queue the time from initiating the scan until the upserting the records takes a really long time. This causes your scan to be really slow even if you have multiple accounts.

Here is an example from my running scanner:

2016-08-09 12:08:55,963 [ search_worker_3][        models][    INFO] Upserted 0 pokemon, 526 pokestops, and 21 gyms
2016-08-09 12:08:56,052 [ search_worker_2][        search][    INFO] Search step 61 beginning (queue size is 30)
2016-08-09 12:09:02,489 [ search_worker_4][        models][    INFO] Upserted 1 pokemon, 514 pokestops, and 18 gyms
2016-08-09 12:09:03,588 [ search_worker_3][        search][    INFO] Search step 62 beginning (queue size is 29)
2016-08-09 12:09:09,174 [ search_worker_5][        models][    INFO] Upserted 2 pokemon, 522 pokestops, and 19 gyms
2016-08-09 12:09:10,063 [ search_worker_4][        search][    INFO] Search step 63 beginning (queue size is 28)
2016-08-09 12:09:15,555 [ search_worker_6][        models][    INFO] Upserted 0 pokemon, 513 pokestops, and 20 gyms
2016-08-09 12:09:16,759 [ search_worker_5][        search][    INFO] Search step 64 beginning (queue size is 27)
2016-08-09 12:09:23,015 [ search_worker_7][        models][    INFO] Upserted 1 pokemon, 554 pokestops, and 21 gyms
2016-08-09 12:09:23,154 [ search_worker_6][        search][    INFO] Search step 65 beginning (queue size is 26)
2016-08-09 12:09:29,785 [ search_worker_8][        models][    INFO] Upserted 2 pokemon, 530 pokestops, and 19 gyms
2016-08-09 12:09:30,576 [ search_worker_7][        search][    INFO] Search step 66 beginning (queue size is 25)
2016-08-09 12:09:36,976 [ search_worker_9][        models][    INFO] Upserted 0 pokemon, 589 pokestops, and 20 gyms
2016-08-09 12:09:37,338 [ search_worker_8][        search][    INFO] Search step 67 beginning (queue size is 24)
2016-08-09 12:09:44,082 [ search_worker_0][        models][    INFO] Upserted 1 pokemon, 562 pokestops, and 19 gyms
2016-08-09 12:09:44,615 [ search_worker_9][        search][    INFO] Search step 68 beginning (queue size is 23)
2016-08-09 12:09:51,677 [ search_worker_0][        search][    INFO] Search step 69 beginning (queue size is 22)
2016-08-09 12:09:52,032 [ search_worker_1][        models][    INFO] Upserted 1 pokemon, 588 pokestops, and 18 gyms
2016-08-09 12:09:59,651 [ search_worker_1][        search][    INFO] Search step 70 beginning (queue size is 21)
2016-08-09 12:10:00,720 [ search_worker_2][        models][    INFO] Upserted 1 pokemon, 621 pokestops, and 17 gyms
2016-08-09 12:10:07,901 [ search_worker_3][        models][    INFO] Upserted 1 pokemon, 585 pokestops, and 18 gyms
2016-08-09 12:10:08,302 [ search_worker_2][        search][    INFO] Search step 71 beginning (queue size is 20)
2016-08-09 12:10:15,423 [ search_worker_4][        models][    INFO] Upserted 0 pokemon, 608 pokestops, and 18 gyms
2016-08-09 12:10:15,476 [ search_worker_3][        search][    INFO] Search step 72 beginning (queue size is 19)
2016-08-09 12:10:22,470 [ search_worker_5][        models][    INFO] Upserted 4 pokemon, 571 pokestops, and 14 gyms

As you can see in the above search_worker_2 took over 60 seconds from beginning of scan to upsert. It if very quick to move from upsert to scan so that isn't an issue. In my setup I am running only 10 accounts in a -st = 6.

I was running an older version of the code before the API change and was not having these issues. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by NoMotion** [comment] 2016-08-09 17:24
I second this. Once you reach too many threads, creating more doesn't help it can actually hurt the speed of the application. I think a large problem is the `time.sleep(sd)` part of each thread. Since we are leaving it up to the OS to handle the threads we don't know for sure if the CPU is spending cycles sleeping when it could be processing another scan.  

Ideally the overseer thread should generate a list of accounts and a timestamp they were last used. If `time.now() - timestamp < scan-delay` then a thread would pick that account and perform the scan. This will ensure there are no `time.sleep` command in the threads and the user should pick an ideal number of threads to handle this 'list' that is best suited for the resources of their host

**Comment by invisiblek** [comment] 2016-08-09 17:58
This is as close as I was able to get it:
`2016-08-09 12:57:33,815 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 1)
2016-08-09 12:57:35,240 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 206 pokestops, and 12 gyms
2016-08-09 12:57:38,815 [ search_worker_0][        search][    INFO] Search step 2 beginning (queue size is 395)
2016-08-09 12:57:39,031 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-09 12:57:43,818 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 394)
2016-08-09 12:57:44,299 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 209 pokestops, and 13 gyms
2016-08-09 12:57:48,818 [ search_worker_0][        search][    INFO] Search step 4 beginning (queue size is 393)
2016-08-09 12:57:48,978 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-09 12:57:53,822 [ search_worker_0][        search][    INFO] Search step 5 beginning (queue size is 392)
2016-08-09 12:57:54,227 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 219 pokestops, and 12 gyms
2016-08-09 12:57:58,822 [ search_worker_0][        search][    INFO] Search step 6 beginning (queue size is 391)
2016-08-09 12:57:58,985 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms`

**Comment by RollTideDG** [comment] 2016-08-09 18:28
Your patch did not fix the issue.
From what I can tell your patch just shortened the delay after upsert but before scan. That wasn't really a problem. The issue is after scan and the delay between upserting. There seems to be a major issue in the threading or the way it is handling threads. 

Below is an example after I applied your patch. Note: in this example I have upped the accounts to 20 with a -st = 6.

2016-08-09 13:22:20,839 [ search_worker_2][        search][    INFO] Search step 24 beginning (queue size is 67)
2016-08-09 13:22:21,220 [ search_worker_3][        search][    INFO] Search step 25 beginning (queue size is 66)
2016-08-09 13:22:21,555 [ search_worker_4][        search][    INFO] Search step 26 beginning (queue size is 65)
2016-08-09 13:22:21,913 [ search_worker_5][        search][    INFO] Search step 27 beginning (queue size is 64)
2016-08-09 13:22:22,270 [ search_worker_6][        search][    INFO] Search step 28 beginning (queue size is 63)
2016-08-09 13:22:22,630 [ search_worker_7][        search][    INFO] Search step 29 beginning (queue size is 62)
2016-08-09 13:22:22,987 [ search_worker_8][        search][    INFO] Search step 30 beginning (queue size is 61)
2016-08-09 13:22:23,346 [ search_worker_9][        search][    INFO] Search step 31 beginning (queue size is 60)
2016-08-09 13:22:23,707 [search_worker_10][        search][    INFO] Search step 32 beginning (queue size is 59)
2016-08-09 13:22:24,072 [search_worker_11][        search][    INFO] Search step 33 beginning (queue size is 58)
2016-08-09 13:22:24,430 [search_worker_12][        search][    INFO] Search step 34 beginning (queue size is 57)
2016-08-09 13:22:24,792 [search_worker_13][        search][    INFO] Search step 35 beginning (queue size is 56)
2016-08-09 13:22:25,151 [search_worker_14][        search][    INFO] Search step 36 beginning (queue size is 55)
2016-08-09 13:22:25,512 [search_worker_15][        search][    INFO] Search step 37 beginning (queue size is 54)
2016-08-09 13:22:25,871 [search_worker_16][        search][    INFO] Search step 38 beginning (queue size is 53)
2016-08-09 13:22:26,229 [search_worker_17][        search][    INFO] Search step 39 beginning (queue size is 52)
2016-08-09 13:22:26,588 [search_worker_18][        search][    INFO] Search step 40 beginning (queue size is 51)
2016-08-09 13:22:27,585 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 575 pokestops, and 17 gyms
2016-08-09 13:22:27,641 [ search_worker_0][        search][    INFO] Search step 41 beginning (queue size is 50)
2016-08-09 13:22:27,641 [search_worker_19][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-09 13:22:27,693 [search_worker_19][        search][    INFO] Search step 42 beginning (queue size is 49)
2016-08-09 13:22:34,061 [ search_worker_1][        models][    INFO] Upserted 1 pokemon, 570 pokestops, and 17 gyms
2016-08-09 13:22:34,102 [ search_worker_1][        search][    INFO] Search step 43 beginning (queue size is 48)
2016-08-09 13:22:41,430 [ search_worker_2][        models][    INFO] Upserted 2 pokemon, 597 pokestops, and 17 gyms
2016-08-09 13:22:41,506 [ search_worker_2][        search][    INFO] Search step 44 beginning (queue size is 47)
2016-08-09 13:22:41,509 [search_worker_20][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-09 13:22:41,539 [search_worker_20][        search][    INFO] Search step 45 beginning (queue size is 46)
2016-08-09 13:22:48,151 [ search_worker_3][        models][    INFO] Upserted 2 pokemon, 540 pokestops, and 17 gyms
2016-08-09 13:22:48,216 [ search_worker_3][        search][    INFO] Search step 46 beginning (queue size is 45)
2016-08-09 13:22:54,836 [ search_worker_4][        models][    INFO] Upserted 0 pokemon, 571 pokestops, and 20 gyms
2016-08-09 13:22:54,901 [ search_worker_4][        search][    INFO] Search step 47 beginning (queue size is 44)
2016-08-09 13:23:02,099 [ search_worker_5][        models][    INFO] Upserted 0 pokemon, 526 pokestops, and 20 gyms
2016-08-09 13:23:02,201 [ search_worker_5][        search][    INFO] Search step 48 beginning (queue size is 43)
2016-08-09 13:23:08,878 [ search_worker_6][        models][    INFO] Upserted 1 pokemon, 529 pokestops, and 18 gyms
2016-08-09 13:23:08,951 [ search_worker_6][        search][    INFO] Search step 49 beginning (queue size is 42)
2016-08-09 13:23:14,857 [ search_worker_7][        models][    INFO] Upserted 0 pokemon, 507 pokestops, and 18 gyms
2016-08-09 13:23:14,946 [ search_worker_7][        search][    INFO] Search step 50 beginning (queue size is 41)
2016-08-09 13:23:21,529 [ search_worker_8][        models][    INFO] Upserted 1 pokemon, 521 pokestops, and 20 gyms
2016-08-09 13:23:21,615 [ search_worker_8][        search][    INFO] Search step 51 beginning (queue size is 40)
2016-08-09 13:23:27,769 [ search_worker_9][        models][    INFO] Upserted 0 pokemon, 511 pokestops, and 18 gyms
2016-08-09 13:23:27,809 [ search_worker_9][        search][    INFO] Search step 52 beginning (queue size is 39)

It seems all the threads are bunching up and not really doing anything. Scanning is extremely slow and adding more accounts only makes the issues worse.

**Comment by NoMotion** [comment] 2016-08-09 18:47
@RollTideDG That's because unless you are running a shit ton of cores you won't get increased performance with more threads. I still feel my first reply is the culprit of this issue and could save a lot of wait time.

**Comment by RollTideDG** [comment] 2016-08-09 19:08
The patch does save some time for sure after the upsert. 

I was running a build from 8/2 before the API change. With 20 accounts I could scan a -st = 6 area in about 90 seconds. With this current build I just grabbed today with the same 20 accounts and -st =6 I am only able to scan in 5-6 minutes. 

Each worker thread is taking 60+ seconds after the initial time through. Before each scan was taking 20 seconds tops.

**Comment by NoMotion** [comment] 2016-08-09 19:22
@RollTideDG What platform are you running this on?

**Comment by RollTideDG** [comment] 2016-08-09 19:31
It's running on a windows7 box.

**Comment by chuyskywalker** [comment] 2016-08-10 04:15
So, I kinda suspect I know what's going on.

'threading' in python aren't really separate threads. (Since we're not using multiprocessing) so all those `sleep` calls may actually be causing a global pause. I need to do some research about this, but I suspect that's what's going on.

If that's the case, we'll need to come up with a better way of letting a thread "let go" of the execution context when it hasn't waited long enough for its "delay" amount.

**Comment by chuyskywalker** [comment] 2016-08-10 04:16
Or I'm totally wrong, according to SO -- http://stackoverflow.com/questions/92928/time-sleep-sleeps-thread-or-process and threads don't block global context.

**Comment by NoMotion** [comment] 2016-08-10 04:32
That article states other threads can still operate when one is sleepin, which is true, but my inclination leads to suspect the CPU might spend a few seconds or so actually sleeping on that process. Not to mention after a process has done its duty it should die and free resources or grab another point and process it, not sit on its resources and sleep

@chuyskywalker do you see my point?

**Comment by chuyskywalker** [comment] 2016-08-10 04:47
No, I don't and it sounds like you're contradicting yourself: "other threads can operate when one is sleeping...the cpu [is] spending a few second sleeping on that process"

If, when in a thread context, time.sleep() releases execution control so other threads can execute, it should not block any other thread from doing work. Some of the basic examples on SO demos this, and running it locally (modeled after how we create threads) it's accurate. `time.sleep()` does not block other threads.

> Not to mention after a ~process~ thread has done its duty it should die and free resources or grab another point and process it, not sit on its resources and sleep

Why would threads be destroyed? You can only have as many threads as you have accounts -- recreating them constantly would be an enormous waste. As for sleeping; that's kind of the entire point of having "scan delay" -- to prevent a single account (thread) from executing more than N requests per timeframe. The API limits being geared towards per-account make that required.

---

I'm not saying there isn't an issue here, but I think you're approaching it wrong.

The [docs on time](https://docs.python.org/2/library/time.html#time.sleep) _do_ say:

> Also, the suspension time may be longer than requested by an arbitrary amount because of the scheduling of other activity in the system.

So perhaps with all the other stuff going on, these `sleep()`s aren't coming back at the interval they should.

**Comment by chuyskywalker** [comment] 2016-08-10 04:51
If you could wrap this around, we could get a better feel for if it's the `sleep()` or not:

```
                    time.sleep(sleep_delay_remaining / 1000)
```

to

```
                    log.info('Search step %s begin delay of ', step, sleep_delay_remaining / 1000)
                    time.sleep(sleep_delay_remaining / 1000)
                    log.info('Search step %s end delay', step)
```

**Comment by NoMotion** [comment] 2016-08-10 05:05
You're right, I guess it is contradicting.... The hair stand up on my neck when I make a thread sleep is all. If possible I'd rather make the thread grab a fresh account and run another scan than sleep. I'll play with that some tomorrow, see what I can find

**Comment by chuyskywalker** [comment] 2016-08-10 07:11
> I'd rather make the thread grab a fresh account and run another scan than sleep

### You. Can't. Do. That

The whole point of thread-per-account is that the API restricts queries per second _by account_. If you scanned as fast as possible with a single thread (read: single account) you would get rate limited, zero results, and possibly even softbanned.

**Comment by NoMotion** [comment] 2016-08-10 07:36
Yea you can do that.... If you keep track of its time stamp and only use one that's older than 10s. If you use enough accounts eventually you wont be able to process enough scans before the first account you used is free

**Comment by invisiblek** [comment] 2016-08-10 13:13
removing milestone, this appears to be working as intended

**Comment by chuyskywalker** [comment] 2016-08-10 14:41
Yeah, ok, I see what you're saying. Keep a list of accounts, indexed by "last used" date. Except, if you do that, things get **_wildly_** over complicated. 

To do that, you'd need to track a global, shared list of accounts and be able to establish locks for each of them. That's a ton of threads trying to manipulate the same shared data (read: not fun). 

Not only that, but now you have to get users to understand how to "balance" threads vs. accounts vs. scan-delay. Right now _(grant, if it was working right)_ it's very straight forward: one account, one scan per `scan-delay` -- easy to understand. Like you're proposing, how would the combo of scan-delay/accounts/threads affect speed? Do you have too few accounts? Or too many threads? Is your scan-delay too high, or too low? For example: with a huge number of accounts, but not enough threads, that's inefficient because some accounts aren't being used as often as they could be. If you flip it around the other way (too many threads, not enough accounts) you end up with a few working threads and a set of **thrashing** threads trying to acquire a lock for an account. Just figuring out if the settings are out of balance would be a huge pain -- trying to communicate that to users would be a nightmare. We couldn't implement "auto-balancing" either. First, it'd be a huge pain, but more importantly, it would create a lot of uncertainty about what the application is doing ("I said 10 threads, why are there only 4?" "I wanted a scan delay of 5 -- why is it using 15?" etc etc)

**Comment by mdnpascual** [comment] 2016-08-10 18:27
Confirming this. Just tested with 16 accounts vs 8 accounts. 8 accounts is scanning faster than 16

**Comment by NoMotion** [comment] 2016-08-10 19:16
@chuyskywalker Definitely agree from the user perspective, no real way to explain it. Just a thought i guess of improving/optimizing its performance.

**Comment by RollTideDG** [comment] 2016-08-10 21:30
Not sure what else I can add but before the API changes when I was using a little bit older version of this map it worked fine. Now it doesn't. My request's using 20 accounts after the first pass through are taking on average of 60 seconds per account. 
If I run just one account then it will send a receive request about every 15 seconds. It like the threads are stepping on each other and causing some sort of blocking.

**Comment by mdnpascual** [comment] 2016-08-10 21:55
It's behaving like it's only using an account @ -sd 3. I switched using the beehive generator for now before this is fixed

**Comment by imynwulf** [comment] 2016-08-10 21:59
Hasn't beehive always been faster? 

Smaller areas with one or two accounts each should update much faster then a comparably sized area with a reasonable number of accounts.

**Comment by mdnpascual** [comment] 2016-08-10 22:01
@imynwulf I have used AHAAA map just before the api change (with multi-account support) and this current one is waaay slower and as I said, it is behaving like it's using 1 account @ -sd 3

**Comment by Bizadon** [comment] 2016-08-11 07:48
So what number of accounts would cause optimum speed? I trying to use 100acc for -st12 (397queue size) with sd 10 and it working like 4,5 minutes instead of ~minute.

**Comment by chuyskywalker** [comment] 2016-08-12 06:06
So, I can't really replicate this, but I only have 8 accounts to play with.

If you modify your `search.py` for the function `search_worker_thread` to this:

```
def search_worker_thread(args, account, search_items_queue, parse_lock, encryption_lib_path):

    # If we have more than one account, stagger the logins such that they occur evenly over scan_delay
    if len(args.accounts) > 1:
        delay = (args.scan_delay / len(args.accounts)) * args.accounts.index(account)
        log.debug('Delaying thread startup for %.2f seconds', delay)
        time.sleep(delay)

    log.debug('Search worker thread starting')

    # The forever loop for the thread
    while True:
        try:
            log.debug('Entering search loop')

            # Create the API instance this will use
            api = PGoApi()
            if args.proxy:
                api.set_proxy({'http': args.proxy, 'https': args.proxy})

            # Get current time
            loop_start_time = int(round(time.time() * 1000))

            # The forever loop for the searches
            while True:

                scantimes = [ ('start', time.time(), 0) ]

                # Grab the next thing to search (when available)
                step, step_location = search_items_queue.get()

                scantimes.append( ('item', time.time(), round((time.time() - scantimes[-1][1]) * 1000)) )

                log.info('Search step %d beginning (queue size is %d)', step, search_items_queue.qsize())

                # Let the api know where we intend to be for this loop
                api.set_position(*step_location)

                scantimes.append( ('setp', time.time(), round((time.time() - scantimes[-1][1]) * 1000)) )

                # The loop to try very hard to scan this step
                failed_total = 0
                while True:

                    # After so many attempts, let's get out of here
                    if failed_total >= args.scan_retries:
                        # I am choosing to NOT place this item back in the queue
                        # otherwise we could get a "bad scan" area and be stuck
                        # on this overall loop forever. Better to lose one cell
                        # than have the scanner, essentially, halt.
                        log.error('Search step %d went over max scan_retires; abandoning', step)
                        break

                    # Increase sleep delay between each failed scan
                    # By default scan_dela=5, scan_retries=5 so
                    # We'd see timeouts of 5, 10, 15, 20, 25
                    sleep_time = args.scan_delay * (1 + failed_total)

                    # Ok, let's get started -- check our login status
                    check_login(args, account, api, step_location)

                    scantimes.append( ('login', time.time(), round((time.time() - scantimes[-1][1]) * 1000)) )

                    api.activate_signature(encryption_lib_path)

                    scantimes.append( ('sig', time.time(), round((time.time() - scantimes[-1][1]) * 1000)) )

                    # Make the actual request (finally!)
                    response_dict = map_request(api, step_location)

                    scantimes.append( ('request', time.time(), round((time.time() - scantimes[-1][1]) * 1000)) )

                    # G'damnit, nothing back. Mark it up, sleep, carry on
                    if not response_dict:
                        log.error('Search step %d area download failed, retrying request in %g seconds', step, sleep_time)
                        failed_total += 1
                        time.sleep(sleep_time)
                        continue

                    # Got the response, lock for parsing and do so (or fail, whatever)
                    with parse_lock:
                        try:
                            parse_map(response_dict, step_location)

                            scantimes.append( ('parse', time.time(), round((time.time() - scantimes[-1][1]) * 1000)) )

                            log.debug('Search step %s completed', step)
                            search_items_queue.task_done()
                            break  # All done, get out of the request-retry loop
                        except KeyError:
                            log.exception('Search step %s map parsing failed, retrying request in %g seconds', step, sleep_time)
                            failed_total += 1
                            time.sleep(sleep_time)

                scantimes.append( ('exec', time.time(), round((time.time() - scantimes[0][1]) * 1000)) )

                # If there's any time left between the start time and the time when we should be kicking off the next
                # loop, hang out until its up.
                sleep_delay_remaining = loop_start_time + (args.scan_delay * 1000) - int(round(time.time() * 1000))
                if sleep_delay_remaining > 0:
                    time.sleep(sleep_delay_remaining / 1000)

                loop_start_time += args.scan_delay * 1000

                scantimes.append( ('delay', time.time(), round((time.time() - scantimes[-1][1]) * 1000)) )
                scantimes.append( ('total', time.time(), time.time() - scantimes[0][1]) )

                log.info('Scan: %s', scantimes)

        # catch any process exceptions, log them, and continue the thread
        except Exception as e:
            log.exception('Exception in search_worker: %s. Username: %s', e, account['username'])
```

It will output pretty detailed timings per thread about where the time-sink is happening at.

**Comment by Bizadon** [comment] 2016-08-12 06:55
@chuyskywalker A lot of errors, they are all simular and just for each worker:
" File ....\search.py line 194 in search worker thread if args.proxy: 
AttributeError: 'Namespace' object has no attribute 'proxy'
2016-08-12 09:50:23,463 [search_worker_16][        search][   ERROR] Exception in search_worker: 'Namespace' object has no attribute 'proxy'. Username: weKecKS8W8NYpwz

**Comment by mdnpascual** [comment] 2016-08-12 07:26
@Bizadon try removing the 2 lines on the line 194 and 195 and try it again. Currently testing this

**Comment by Bizadon** [comment] 2016-08-12 07:57
Yeah, it just began a x2 faster - 2,5 minutes with 80 workers and st10 instead of 5 minutes.

**Comment by chuyskywalker** [comment] 2016-08-12 13:15
I had a mistake above, where "parse" time includes time spent waiting for the lock. Adding another line here:
```
                    with parse_lock:
                        scantimes.append( ('lkaq', time.time(), round((time.time() - scantimes[-1][1]) * 1000)) )
                        try:
                            parse_map(response_dict, step_location)

                            scantimes.append( ('parse', time.time(), round((time.time() - scantimes[-1][1]) * 1000)) )
```
(The `lkaq` line) so we see see those times.

As more threads spin up, you can see the lock acquire time goes up and up:

```
 Scan: [('start', 1471007684.242001, 0), ('item', 1471007684.242103, 0.0), ('setp', 1471007684.243903, 2.0), ('login', 1471007684.243995, 0.0), ('sig', 1471007684.244034, 0.0), ('request', 1471007685.562468, 1318.0), ('lkaq', 1471007699.140037, 13578.0), ('parse', 1471007701.681992, 2542.0), ('exec', 1471007701.682085, 17440.0), ('delay', 1471007701.682108, 0.0), ('total', 1471007701.682114, 17.440112829208374)]
```

So parsing itself isn't quite so bad (1-3 seconds) but with a lot of threads going on, the locking gets progressively worse.

**Comment by chuyskywalker** [comment] 2016-08-12 13:27
For the heck of it, I tried removing the lock:

```
2016-08-12 13:24:09,131 [ search_worker_1][        models][ WARNING] database is locked... Retrying
2016-08-12 13:24:09,133 [ search_worker_0][        models][ WARNING] database is locked... Retrying
2016-08-12 13:24:09,135 [ search_worker_1][        models][ WARNING] database is locked... Retrying
2016-08-12 13:24:09,136 [ search_worker_0][        models][ WARNING] database is locked... Retrying
2016-08-12 13:24:09,138 [ search_worker_1][        models][ WARNING] database is locked... Retrying
2016-08-12 13:24:09,781 [ search_worker_3][      auth_ptc][    INFO] PTC User Login successful.
2016-08-12 13:24:09,786 [ search_worker_3][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-12 13:24:10,075 [ search_worker_3][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-12 13:24:10,309 [ search_worker_7][        models][    INFO] Upserted 2 pokemon, 640 pokestops, and 17 gyms
2016-08-12 13:24:10,313 [ search_worker_7][        search][    INFO] Scan: [
 ('start', 1471008224.179017, 0), 
 ('item', 1471008224.179053, 0.0), 
 ('setp', 1471008224.179269, 0.0), 
 ('login', 1471008224.179313, 0.0), 
 ('sig', 1471008224.17932, 0.0), 
 ('request', 1471008227.142678, 2963.0), 
 ('parse', 1471008250.313582, 23171.0), 
 ('exec', 1471008250.31367, 26135.0), 
 ('delay', 1471008250.313688, 0.0), 
 ('total', 1471008250.313701, 26.134683847427368)]
```
Does not go well at all.

**Comment by chuyskywalker** [comment] 2016-08-13 17:53
Y'all should give the branch in #582 a try.

**Comment by hemsleyk** [comment] 2016-08-14 03:49
I will try that branch ... I can throw 25 accounts at it. What step limit for 25 accts, 20?

**Comment by hemsleyk** [comment] 2016-08-14 07:26
Preliminary testing is promising ... 20 step area with 20 accounts is more than keeping up with one using 70. Identical SQL database setup (load-balanced Galera+MariaDB cluster).

**Comment by pyr0ball** [comment] 2016-08-19 08:23
Checking in to see if this issue is resolved

**Comment by chuyskywalker** [comment] 2016-08-19 13:25
582 was merged and should pretty much resolve this. Y'all may need to tweak `--db-threads` depending on your account counts, but it's tuneable for a reason :D

**Closed by chuyskywalker** 2016-08-19 13:25 UTC
Labels: backend, bugfix
