### ISSUE TITLE
0 upsert after a re-login (with -ss)

### ISSUE THREAD

**Issue by Becold** [PokemonGoMap/PokemonGo-Map#847] opened 2016-08-19 16:25 UTC
## Expected Behavior
Getting pokestop or gyms after a re-login.

## Current Behavior
Got 0/0/0.

## Possible Solution
Maybe flag the spawnpoints and retry it 30 seconds after. If again 0/0/0, flag the spawnpoints + accounts somewhere (in an output file).
Maybe the spawnpoints changed.

## Steps to Reproduce (for bugs)
Run this script : 
`python runserver.py -os -l 'myass'  `
`python runserver.py -ns -ss spawnpoints.json -l 'myass' -sd 15 -ld 11 --db-max_connections 100`
And wait until the script need to re-login the accounts.

My logs : http://puu.sh/qH1fS/d1980dc03b.png

## Context
Guess it doesnt scan pokemons properly.

## Your Environment
* Version used: My last commit is 4a27fd01c2e52809c96adc94ae63cc12a073249a
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Linux debian 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) i686 GNU/Linux

**Comment by Draag** [comment] 2016-08-19 17:30
Please don't close this or merge it with the other one that mine got swept into, this issue is specifically after RE-authenticating. It's not the same as the other one which was producing 0/0/0 after initially starting the server.

**Comment by pyr0ball** [comment] 2016-08-19 18:00
I observed similar behavior like this last week, but haven't had a chance to trace the cause yet. Could still be configuration issue, but will need further investigation.

**Comment by mda8** [comment] 2016-08-19 18:16
had a similar issue and it got merged with #462 too. See #821

**Comment by BaIthamel** [comment] 2016-08-20 01:40
I'm so confident they're related, I'm pretty sure we don't reauthorize yet we just log in again, so this would be the same as errors after logging in the first time.

**Closed** 2016-08-22 18:45 UTC
