### ISSUE TITLE
Lured Pokemon Dont Show Anymore

### ISSUE THREAD

**Issue by SkOODaT** [PokemonGoMap/PokemonGo-Map#242] opened 2016-08-09 00:19 UTC
Lured pokemon dont show icons anymore on the map

**Comment by BaIthamel** [comment] 2016-08-09 00:19
duplicate of #131

**Closed by BaIthamel** 2016-08-09 00:19 UTC

**Comment by SkOODaT** [comment] 2016-08-09 00:20
sorry too may issues tried to see if thier was one as long as you guys are aware :)
