### ISSUE TITLE
Crashing while login

### ISSUE THREAD

**Issue by aididhaiqal** [PokemonGoMap/PokemonGo-Map#486] opened 2016-08-11 11:55 UTC
## Expected Behavior
While login in,Exception threwed
## Current Behavior
2016-08-11 19:54:18,061 [search_worker_69][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-11 19:54:18,069 [search_worker_399][        search][   ERROR] Exception in search_worker: ("bad handshake: SysCallError(10053, 'WSAECONNABORTED')",)
Traceback (most recent call last):
  File "C:\Users\aidid\Desktop\Pokemon GO Map\pogom\search.py", line 228, in search_worker_thread
    check_login(args, account, api, step_location)
  File "C:\Users\aidid\Desktop\Pokemon GO Map\pogom\search.py", line 281, in check_login
    api.set_authentication(provider=account['auth_service'], username=account['username'], password=account['password'])
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 87, in set_authentication
    self._auth_provider.user_login(username, password)
  File "C:\Python27\lib\site-packages\pgoapi\auth_ptc.py", line 63, in user_login
    r = self._session.get(self.PTC_LOGIN_URL, headers=head)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
## Steps to Reproduce (for bugs)
1.Add 600 acc to the config
2.Wait
3.Error comming up
4.

## Your Environment

* Version used: Latest
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Desktop

**Comment by djv2** [comment] 2016-08-11 14:00
same issue. i set login delay -ld 20 and still happens

**Comment by marumari** [comment] 2016-08-11 14:48
This is a duplicate of #392.

**Closed** 2016-08-11 15:56 UTC
Labels: duplicate
