### ISSUE TITLE
Feature request- on status page a toggle to start stop scanner

### ISSUE THREAD

**Issue by TRingo1** [PokemonGoMap/PokemonGo-Map#1198] opened 2016-09-07 12:04 UTC
I want to start and stop the scanner engine while hunting and not leave the scanner running continuously 

## Expected Behavior

Scanner is always running if the server is started with the script. The ability to start and stop the scanner engine would be good.  And when on the status page the ability to verify a success username password authenticity 

## Possible Solution

When you are on the secure login page for the worker status it would be very nice to have the ability to start and stop the scanning process.

**Comment by justsomedudeonthenet** [comment] 2016-09-07 13:38
Duplicate of #1156

**Closed by justsomedudeonthenet** 2016-09-07 13:38 UTC
