### ISSUE TITLE
Feature request : add the "life" of a gym

### ISSUE THREAD

**Issue by cyan** [PokemonGoMap/PokemonGo-Map#1399] opened 2016-09-27 10:35 UTC
#hi,
i think it would be nice to add in the gym windows the time for how long it has been the same color. (in some country there a lot of gyms that don't change that much).
it would help us know if it's a "safe" gym to defend for coins xD

PS : thanks again for your great work guys

**Comment by springjools** [comment] 2016-09-27 11:08
See #1211

**Comment by cyan** [comment] 2016-09-27 11:10
my bad, haven't searched with the right words xD (you can delete this feature request then plz)

**Comment by springjools** [comment] 2016-09-27 11:14
I just thought it's best to have the discussion in one place

**Comment by beccasafan** [comment] 2016-09-27 18:13
Closing as a dupe of #1211.

**Closed by beccasafan** 2016-09-27 18:13 UTC
