### ISSUE TITLE
Everything is be coming much slower

### ISSUE THREAD

**Issue by xioxxio** [PokemonGoMap/PokemonGo-Map#1087] opened 2016-09-01 11:03 UTC
I dont need to write an essay to notice the speed difference over the last few days.  Everything is much slower.

I am not sure what can be done but there must be some speed optimization vs all the bells and whistles.

**Comment by aldarund** [comment] 2016-09-01 11:23
So good ticket. Zero actual info.

**Comment by Dagothur** [comment] 2016-09-01 11:37
It's slower because your computer is dirty. Throw it into the tub for 30 minutes.

**Comment by xioxxio** [comment] 2016-09-01 12:01
@Dagothur OMG, you are a genius, thanks that worked.

@aldarund Lets stop and think about this.  If I knew what was causing the problem, I would say so.

**Comment by angrymoose** [comment] 2016-09-01 12:02
@Dagothur that sounds like an excellent idea, it'll definitely help @xioxxio improve his scans.

However this ticket issue is useless without any actual details, or bugs reported.

**Comment by aldarund** [comment] 2016-09-01 12:05
@xioxxio u dont need to know what causing.U need to describe problem. Everythin slower not a problem. Its have zero info. Zero usefulness. It just a rant

**Comment by xioxxio** [comment] 2016-09-01 12:08
I setup a new db, I am running both versions now. old and new.  There is a huge difference in speed.  As an example, I have pokealarm running on both systems.  There is 2 minutes difference in the alert time between the new and old

Also scan speed are much slower pokemon appear at least a minute between the systems.

**Comment by aldarund** [comment] 2016-09-01 12:15
what is old version. what is new version... 
could be https://github.com/PokemonGoMap/PokemonGo-Map/issues/1082

**Comment by xioxxio** [comment] 2016-09-01 12:30
commit id cac3932eff4cdfb99f85d6ae92d69c4f547d4556 for the new version
commit id 083b05a4157825500ab84337ed1e6aad7c982c7b for the old version

**Comment by aldarund** [comment] 2016-09-01 13:01
So obv its a gevent issue that i linked.

**Comment by xioxxio** [comment] 2016-09-01 13:13
The difference is day and night in speed (scanning speed of pokemon)

**Comment by nhumber** [comment] 2016-09-01 13:35
Issues here too,  ran last flask commit without issue. Ran gevent commit without issue for a 8 hours, woke up today and I had to reboot my server. It took over 3 minutes to load around 3500 Pokémon on the screen where as with flask it took 2 seconds, now that im rebooted performance is back to normal. Will update in another 12 hours with proper issue if it happens again.imo gevent fixed those database fetch issues I saw occasionally, but has broken something else.

**Comment by aldarund** [comment] 2016-09-01 17:14
its dupe of https://github.com/PokemonGoMap/PokemonGo-Map/issues/1082

**Comment by c133** [comment] 2016-09-01 18:49
My pokealarm on gevent times to despawn for each pokemon are still all ~14 minutes like before with flask so I think it is still getting stuff on time

@xioxxio what is radius in km of your scan area?

**Comment by pyr0ball** [comment] 2016-09-01 23:01
Please follow the bug submission requirements. This may be an actual bug but without data / debug information we cannot do anything about it. If you're unsure how to gather this information, post on the discord channel, or on the [support forum](http://pokemongo-map.me)

**Closed by pyr0ball** 2016-09-01 23:01 UTC
Labels: issues are not for support!, not a bug - server issue
