### ISSUE TITLE
TB scanner.

### ISSUE THREAD

**Issue by BaIthamel** [PokemonGoMap/PokemonGo-Map#608] opened 2016-08-13 13:22 UTC
Implementing TB's intelligent scan improvment

Requirements.

1. Create a file with locations and times, potentially multiple to avoid scanners jumping stupid distances and getting banned (if you have a map with multiple workers in different places) one file per worker.
This is already mostly done in #585 
DONE

2. Implementing the Tb scan into the search.py. what was done here https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/ is probably a good place to look. However we will want flags to search inaddition to 14 mins before despawn 29 and 44 mins to ensure we catch 45 min spawns with all their time.
MOSTLY DONE still needs 29 44 min option

Did I miss anything?

**Comment by FeikoWielsma** [comment] 2016-08-13 14:10
https://github.com/PokemonGoMap/PokemonGo-Map/pull/585 already modified the search.py too, you'd only need to add the flags for the 29 / 44 stuff

**Comment by marumari** [comment] 2016-08-13 14:31
Is this not a duplicate of #390 and #179?

**Comment by FeikoWielsma** [comment] 2016-08-13 14:33
#390 just shows the spawnpoints on the map, #179 is an optimization for the beehive technique, this is just another scanning algorithm altogether

**Comment by chuyskywalker** [comment] 2016-08-13 18:34
#179  for more

**Comment by blindreaper** [comment] 2016-08-14 14:51
PR Welcome :+1:

**Comment by blindreaper** [comment] 2016-08-15 00:50
Does 3 mean scan the pokestop every 3 minutes if lured? 

Can you elaborate on 2?

Any thoughts on how spawns. json should be generated?  An argument like -generate "new york" -range 50km? a seperate script to pull data?

**Comment by invisiblek** [comment] 2016-08-22 03:29
this can be closed now right?

#3 is not relevant to the title....

**Comment by BaIthamel** [comment] 2016-08-22 18:38
Well tbterra needs some sort of lure pokestop scan but i removed it @invisiblek i'd say it can be closed if it's the only thing left stopping 3.2

**Closed** 2016-09-02 03:33 UTC
